// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as RaisingField from "../../../src/RaisingField.mjs";

function testEqual(t, name, lhs, rhs) {
  t.test(name, async t => {
    t.equal(lhs, rhs, name);
  });
}

Zora.test("option field with a raising legacy codec", t => {
  let sample = {
    label: null,
    value: null
  };
  let sampleJson = sample;
  let decoded = RaisingField.t_decode(sampleJson);
  t.test("null decodes to None when the inner decoder raises", async t => {
    if (decoded.TAG === "Ok") {
      let record = decoded._0;
      t.equal(record.label, undefined, "label");
      t.equal(record.value, undefined, "value");
      return;
    }
    t.fail("expected decode to succeed");
  });
  let sample2 = {
    label: "a",
    value: "b"
  };
  let sampleJson2 = sample2;
  let decoded2 = RaisingField.t_decode(sampleJson2);
  t.test("present values still decode", async t => {
    if (decoded2.TAG === "Ok") {
      let record = decoded2._0;
      t.equal(record.label, "a", "label");
      t.equal(record.value, "b", "value");
      return;
    }
    t.fail("expected decode to succeed");
  });
  let encoded = RaisingField.t_encode({
    label: "a",
    value: "b"
  });
  testEqual(t, "encode", encoded, {
    label: "a",
    value: "b"
  });
});

export {
  testEqual,
}
/*  Not a pure module */
