// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as Serde from "../../../src/Serde.mjs";
import * as Spice from "../../../src/Spice.mjs";
import * as SerdeEdge from "../../../src/SerdeEdge.mjs";
import * as SerdeIface from "../../../src/SerdeIface.mjs";
import * as Stdlib_Result from "@rescript/runtime/lib/es6/Stdlib_Result.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function testEqual(t, name, lhs, rhs) {
  t.test(name, async t => {
    t.equal(lhs, rhs, name);
  });
}

function json(prim0, prim1) {
  return JSON.parse(prim0, prim1 !== undefined ? Primitive_option.valFromOption(prim1) : undefined);
}

function errorAt(result) {
  if (result.TAG === "Ok") {
    return;
  }
  let match = result._0;
  return [
    match.path,
    match.message
  ];
}

function roundTrips(t, name, values, encode, decode) {
  testEqual(t, name, values.map(v => decode(encode(v))), values.map(v => ({
    TAG: "Ok",
    _0: v
  })));
}

Zora.test("@spice.serde mutually recursive types", t => {
  let value = {
    TAG: "Add",
    left: {
      TAG: "Num",
      _0: 1
    },
    right: {
      op: "Wrap",
      inner: {
        TAG: "Neg",
        _0: "Zero"
      }
    }
  };
  testEqual(t, "encode mixes external and internal tags", SerdeEdge.expr_encode(value), JSON.parse(`{"Add":{"left":{"Num":1},"right":{"op":"Wrap","inner":{"Neg":{"op":"Zero"}}}}}`));
  roundTrips(t, "round trip", [
    value,
    {
      TAG: "Num",
      _0: -1
    },
    {
      TAG: "Neg",
      _0: {
        op: "Lit",
        value: 2
      }
    },
    {
      TAG: "Add",
      left: value,
      right: "Zero"
    }
  ], SerdeEdge.expr_encode, SerdeEdge.expr_decode);
  testEqual(t, "external error path", errorAt(SerdeEdge.expr_decode(JSON.parse(`{"Add":{"left":{"Num":"x"},"right":"Zero"}}`))), [
    ".Add.left.Num",
    "Not a number"
  ]);
  testEqual(t, "internal error path", errorAt(SerdeEdge.expr_decode(JSON.parse(`{"Add":{"left":{"Num":1},"right":{"op":"Lit","value":"no"}}}`))), [
    ".Add.right.value",
    "Not a number"
  ]);
});

Zora.test("@spice.serde field names used by generated code", t => {
  let fields = `{"v":1,"dict":2,"payload":3,"json_arr":4,"spice_tag":5,"e":6}`;
  testEqual(t, "externally tagged", SerdeEdge.ext_decode(JSON.parse(`{"Clash":` + fields + `}`)), {
    TAG: "Ok",
    _0: {
      TAG: "Clash",
      v: 1,
      dict: 2,
      payload: 3,
      json_arr: 4,
      spice_tag: 5,
      e: 6
    }
  });
  testEqual(t, "internally tagged", SerdeEdge.int__decode(JSON.parse(`{"type":"Clash",` + fields.slice(1))), {
    TAG: "Ok",
    _0: {
      type: "Clash",
      v: 1,
      dict: 2,
      payload: 3,
      json_arr: 4,
      spice_tag: 5,
      e: 6
    }
  });
  testEqual(t, "plain @spice record", SerdeEdge.record_decode(JSON.parse(`{"v":1,"dict":2,"e":3,"decoder_a":4}`)), {
    TAG: "Ok",
    _0: {
      v: 1,
      dict: 2,
      e: 3,
      decoder_a: 4
    }
  });
});

Zora.test("@spice.serde record field attributes and types", t => {
  let value = {
    type: "Fields",
    name: "ab",
    count: 1,
    optional: "o",
    nullable: 3,
    list: {
      hd: 1,
      tl: {
        hd: 2,
        tl: /* [] */0
      }
    },
    tuple: [
      1,
      "x"
    ],
    result: {
      TAG: "Error",
      _0: "e"
    }
  };
  testEqual(t, "encode", SerdeEdge.fields_encode(value), JSON.parse(`{"type":"Fields","name":"AB","count":1,"optional":"o","nullable":3,"list":[1,2],"tuple":[1,"x"],"result":["Error","e"]}`));
  roundTrips(t, "round trip", [
    value,
    {
      type: "Fields",
      name: "",
      count: 0,
      optional: "",
      nullable: null,
      list: /* [] */0,
      tuple: [
        0,
        ""
      ],
      result: {
        TAG: "Ok",
        _0: 0
      }
    }
  ], SerdeEdge.fields_encode, SerdeEdge.fields_decode);
  testEqual(t, "@spice.default and an absent optional field", Stdlib_Result.map(SerdeEdge.fields_decode(JSON.parse(`{"type":"Fields","name":"AB","nullable":null,"list":[],"tuple":[1,"x"],"result":["Ok",1]}`)), SerdeEdge.fields_encode), {
    TAG: "Ok",
    _0: JSON.parse(`{"type":"Fields","name":"AB","count":7,"nullable":null,"list":[],"tuple":[1,"x"],"result":["Ok",1]}`)
  });
  testEqual(t, "a missing required field", errorAt(SerdeEdge.fields_decode(JSON.parse(`{"type":"Fields","name":"AB","list":[],"tuple":[1,"x"],"result":["Ok",1]}`))), [
    ".nullable",
    "nullable missing"
  ]);
});

Zora.test("@spice.serde generic types", t => {
  let encode = SerdeEdge.gen_encode(Spice.intToJson)(Spice.stringToJson);
  let decode = SerdeEdge.gen_decode(Spice.intFromJson)(Spice.stringFromJson);
  testEqual(t, "encode", [
    {
      TAG: "One",
      _0: 1
    },
    {
      TAG: "Two",
      _0: 1,
      _1: "b"
    },
    {
      TAG: "Rec",
      a: 1,
      b: ["x"]
    },
    "Nothing"
  ].map(encode), [
    JSON.parse(`{"One":1}`),
    JSON.parse(`{"Two":[1,"b"]}`),
    JSON.parse(`{"Rec":{"a":1,"b":["x"]}}`),
    JSON.parse(`"Nothing"`)
  ]);
  roundTrips(t, "round trip", [
    {
      TAG: "One",
      _0: 1
    },
    {
      TAG: "Two",
      _0: 1,
      _1: "b"
    },
    {
      TAG: "Rec",
      a: 1,
      b: []
    },
    "Nothing"
  ], encode, decode);
  testEqual(t, "legacy", decode(JSON.parse(`["Two",1,"b"]`)), {
    TAG: "Ok",
    _0: {
      TAG: "Two",
      _0: 1,
      _1: "b"
    }
  });
  testEqual(t, "tuple error path", errorAt(decode(JSON.parse(`{"Two":[1,2]}`))), [
    ".Two[1]",
    "Not a string"
  ]);
  testEqual(t, "record error path", errorAt(decode(JSON.parse(`{"Rec":{"a":1,"b":[2]}}`))), [
    ".Rec.b[0]",
    "Not a string"
  ]);
});

Zora.test("@spice.serde options in payloads", t => {
  testEqual(t, "None is null", SerdeEdge.opt_encode({
    TAG: "Some_",
    _0: undefined
  }), JSON.parse(`{"Some_":null}`));
  testEqual(t, "null is None", SerdeEdge.opt_decode(JSON.parse(`{"Some_":null}`)), {
    TAG: "Ok",
    _0: {
      TAG: "Some_",
      _0: undefined
    }
  });
  testEqual(t, "a value is Some", SerdeEdge.opt_decode(JSON.parse(`{"Some_":3}`)), {
    TAG: "Ok",
    _0: {
      TAG: "Some_",
      _0: 3
    }
  });
  testEqual(t, "options in an array", SerdeEdge.opt_encode({
    TAG: "Arr",
    _0: [
      1,
      undefined
    ]
  }), JSON.parse(`{"Arr":[1,null]}`));
  testEqual(t, "an array with nulls", SerdeEdge.opt_decode(JSON.parse(`{"Arr":[1,null]}`)), {
    TAG: "Ok",
    _0: {
      TAG: "Arr",
      _0: [
        1,
        undefined
      ]
    }
  });
});

Zora.test("@spice.serde names", t => {
  testEqual(t, "non-ASCII", SerdeEdge.unicode_encode("Hana"), JSON.parse(`"하나"`));
  testEqual(t, "with a space", SerdeEdge.unicode_encode("Space"), JSON.parse(`"with space"`));
  testEqual(t, "empty", SerdeEdge.unicode_encode("Empty"), JSON.parse(`""`));
  roundTrips(t, "round trip", [
    "Hana",
    "Space",
    "Empty"
  ], SerdeEdge.unicode_encode, SerdeEdge.unicode_decode);
  testEqual(t, "a single constructor", SerdeEdge.single_encode("Only"), JSON.parse(`"Only"`));
  testEqual(t, "a single tagged constructor", SerdeEdge.singleTagged_encode({
    type: "OnlyTagged",
    x: 1
  }), JSON.parse(`{"type":"OnlyTagged","x":1}`));
});

Zora.test("@spice.serde decode and encode only", t => {
  testEqual(t, "decode only", SerdeEdge.decodeOnly_decode(JSON.parse(`{"D2":1}`)), {
    TAG: "Ok",
    _0: {
      TAG: "D2",
      _0: 1
    }
  });
  testEqual(t, "encode only", SerdeEdge.encodeOnly_encode({
    TAG: "E2",
    _0: 1
  }), JSON.parse(`{"E2":1}`));
});

Zora.test("@spice.serde with an interface", t => {
  testEqual(t, "variant", SerdeIface.t_encode({
    type: "B",
    x: 1
  }), JSON.parse(`{"type":"B","x":1}`));
  testEqual(t, "polyvariant", SerdeIface.p_encode({
    NAME: "B",
    VAL: 1
  }), JSON.parse(`{"B":1}`));
  testEqual(t, "decode", SerdeIface.t_decode(JSON.parse(`{"type":"A"}`)), {
    TAG: "Ok",
    _0: "A"
  });
});

Zora.test("@spice.serde rejected input", t => {
  let expr = s => errorAt(SerdeEdge.expr_decode(JSON.parse(s)));
  let term = s => errorAt(SerdeEdge.term_decode(JSON.parse(s)));
  testEqual(t, "a number", expr(`5`), [
    "",
    "Not a variant"
  ]);
  testEqual(t, "a boolean", expr(`true`), [
    "",
    "Not a variant"
  ]);
  testEqual(t, "null", expr(`null`), [
    "",
    "Not a variant"
  ]);
  testEqual(t, "tagged null", term(`null`), [
    "",
    "Not a variant"
  ]);
  testEqual(t, "a polyvariant null", errorAt(Serde.poly_decode(JSON.parse(`null`))), [
    "",
    "Not a variant"
  ]);
  testEqual(t, "a null record payload", expr(`{"Add":null}`), [
    ".Add",
    "Not an object"
  ]);
  testEqual(t, "a null single payload", expr(`{"Num":null}`), [
    ".Num",
    "Not a number"
  ]);
  testEqual(t, "a null tuple payload", errorAt(SerdeEdge.gen_decode(Spice.intFromJson)(Spice.stringFromJson)(JSON.parse(`{"Two":null}`))), [
    ".Two",
    "Not an array"
  ]);
  testEqual(t, "a null inside a tagged single value", errorAt(Serde.internal_decode(JSON.parse(`{"type":"Point","x":null}`))), [
    ".x",
    "Not a number"
  ]);
  testEqual(t, "an empty array", expr(`[]`), [
    "",
    "Expected variant, found empty array"
  ]);
  testEqual(t, "an empty object", expr(`{}`), [
    "",
    "Expected an object with one key"
  ]);
  testEqual(t, "two keys", expr(`{"Num":1,"Neg":"Zero"}`), [
    "",
    "Expected an object with one key"
  ]);
  testEqual(t, "an unknown name", expr(`{"Mul":1}`), [
    "",
    "Invalid variant constructor"
  ]);
  testEqual(t, "a payload name as a string", expr(`"Num"`), [
    "",
    "Invalid variant constructor"
  ]);
  testEqual(t, "a tuple that isn't an array", errorAt(SerdeEdge.gen_decode(Spice.intFromJson)(Spice.stringFromJson)(JSON.parse(`{"Two":1}`))), [
    ".Two",
    "Not an array"
  ]);
  testEqual(t, "a record that isn't an object", expr(`{"Add":1}`), [
    ".Add",
    "Not an object"
  ]);
  testEqual(t, "a unit with a value", errorAt(SerdeEdge.single_decode(JSON.parse(`{"Only":1}`))), [
    ".Only",
    "Expected null"
  ]);
  testEqual(t, "a unit with null", SerdeEdge.single_decode(JSON.parse(`{"Only":null}`)), {
    TAG: "Ok",
    _0: "Only"
  });
  testEqual(t, "legacy wrong arity", expr(`["Num"]`), [
    "",
    "Invalid number of arguments to variant constructor"
  ]);
  testEqual(t, "legacy unknown name", expr(`["Mul",1]`), [
    "",
    "Invalid variant constructor"
  ]);
  testEqual(t, "a missing tag", term(`{"value":1}`), [
    "",
    "op missing"
  ]);
  testEqual(t, "a tag that isn't a string", term(`{"op":1}`), [
    "",
    "op missing"
  ]);
  testEqual(t, "an unknown tag", term(`{"op":"Mul"}`), [
    "",
    "Invalid variant constructor"
  ]);
  testEqual(t, "an unknown bare name", term(`"Mul"`), [
    "",
    "Invalid variant constructor"
  ]);
  testEqual(t, "extra keys on a unit are ignored, like serde", SerdeEdge.term_decode(JSON.parse(`{"op":"Zero","x":1}`)), {
    TAG: "Ok",
    _0: "Zero"
  });
});

export {
  testEqual,
  json,
  errorAt,
  roundTrips,
}
/*  Not a pure module */
