// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as Spice from "../../../src/Spice.mjs";
import * as Nodefs from "node:fs";
import * as SerdeRust from "../../../src/SerdeRust.mjs";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_string from "@rescript/runtime/lib/es6/Primitive_string.js";

let golden = Stdlib_Option.getOrThrow(Stdlib_JSON.Decode.object(JSON.parse(Nodefs.readFileSync("fixtures/serde-rust.json", "utf8"))), undefined);

let used = {
  contents: []
};

function check(t, name, value, encode, decode) {
  used.contents = used.contents.concat([name]);
  let json = Stdlib_Option.getOrThrow(golden[name], undefined);
  t.test(name, async t => {
    t.equal(encode(value), json, name + " encodes like serde");
    t.equal(decode(json), {
      TAG: "Ok",
      _0: value
    }, name + " decodes serde's JSON");
  });
}

Zora.test("@spice.serde matches Rust serde", t => {
  let size = (name, v) => check(t, name, v, SerdeRust.size_encode, SerdeRust.size_decode);
  let poly = (name, v) => check(t, name, v, SerdeRust.poly_encode, SerdeRust.poly_decode);
  let ext = (name, v) => check(t, name, v, SerdeRust.ext_encode, SerdeRust.ext_decode);
  let int = (name, v) => check(t, name, v, SerdeRust.int__encode, SerdeRust.int__decode);
  let gen = (name, v) => check(t, name, v, SerdeRust.gen_encode(extra => Spice.arrayToJson(Spice.stringToJson, extra)), SerdeRust.gen_decode(extra => Spice.arrayFromJson(Spice.stringFromJson, extra)));
  size("size_s", "S");
  size("size_l", "L");
  poly("poly_left", "Left");
  poly("poly_right", "Right");
  poly("poly_payload", {
    NAME: "Payload",
    VAL: -3
  });
  poly("poly_pair", {
    NAME: "Pair",
    VAL: [
      `a"b`,
      true
    ]
  });
  ext("ext_unit", "Unit");
  ext("ext_renamed", "Renamed");
  ext("ext_two", "Two");
  ext("ext_single", {
    TAG: "Single",
    _0: 7
  });
  ext("ext_float", {
    TAG: "Float",
    _0: 1.5
  });
  ext("ext_pair", {
    TAG: "Pair",
    _0: "x",
    _1: false
  });
  ext("ext_rec", {
    TAG: "Rec",
    a: "a",
    b: 2
  });
  ext("ext_rec_none", {
    TAG: "Rec",
    a: "a",
    b: undefined
  });
  ext("ext_opt_some", {
    TAG: "Opt",
    _0: 1
  });
  ext("ext_opt_none", {
    TAG: "Opt",
    _0: undefined
  });
  ext("ext_list", {
    TAG: "List",
    _0: [
      1,
      2,
      3
    ]
  });
  ext("ext_list_empty", {
    TAG: "List",
    _0: []
  });
  ext("ext_map", {
    TAG: "Map",
    _0: Object.fromEntries([
      [
        "a",
        1
      ],
      [
        "b",
        2
      ]
    ])
  });
  ext("ext_nested", {
    TAG: "Nested",
    _0: {
      TAG: "Nested",
      _0: "Unit"
    }
  });
  ext("ext_point", {
    TAG: "Point",
    _0: {
      x: 1,
      y: -2
    }
  });
  int("int_regular", "Regular");
  int("int_overlap", {
    type: "Overlap",
    cameraSize: "L"
  });
  int("int_full", {
    type: "Full",
    screenFit: "cover",
    punchIn: true
  });
  int("int_point", {
    type: "Point",
    _0: {
      x: 3,
      y: 4
    }
  });
  int("int_map", {
    type: "Map",
    _0: Object.fromEntries([[
        "k",
        5
      ]])
  });
  int("int_map_empty", {
    type: "Map",
    _0: {}
  });
  check(t, "nested", {
    kind: "SideBySide",
    position: {
      NAME: "Pair",
      VAL: [
        "p",
        false
      ]
    },
    style: {
      type: "Overlap",
      cameraSize: "M"
    }
  }, SerdeRust.nested_encode, SerdeRust.nested_decode);
  gen("gen_g", {
    type: "G",
    value: [
      "a",
      "b"
    ]
  });
  gen("gen_e", "E");
  check(t, "tree", {
    TAG: "Node",
    left: "Leaf",
    right: {
      TAG: "Node",
      left: "Leaf",
      right: "Leaf",
      value: 2
    },
    value: 1
  }, SerdeRust.tree_encode, SerdeRust.tree_decode);
  t.test("with_null: serde's null for None decodes", async t => {
    t.equal(SerdeRust.withNull_decode(Stdlib_Option.getOrThrow(golden["with_null"], undefined)), {
      TAG: "Ok",
      _0: {
        type: "N",
        b: undefined
      }
    }, "with_null");
  });
  used.contents = used.contents.concat(["with_null"]);
  t.test("every golden case is checked", async t => {
    t.equal(used.contents.toSorted(Primitive_string.compare), Object.keys(golden).toSorted(Primitive_string.compare), "cases");
  });
});

export {
  golden,
  used,
  check,
}
/* golden Not a pure module */
