// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as SerdeRust from "../../../src/SerdeRust.mjs";
import * as SerdeLegacy from "../../../src/SerdeLegacy.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_Result from "@rescript/runtime/lib/es6/Stdlib_Result.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let seed = {
  contents: 42
};

function next(bound) {
  seed.contents = (seed.contents * 1103515245 | 0) + 12345 & 2147483647;
  return Primitive_int.mod_(seed.contents / 65536 | 0, bound);
}

function int() {
  return next(2001) - 1000 | 0;
}

function string() {
  return Stdlib_Option.getOr([
      "",
      "a",
      "둘",
      `q"uote`,
      "back\\slash",
      "type"
    ][next(6)], "");
}

function ext(depth) {
  let match = next(depth > 3 ? 11 : 12);
  switch (match) {
    case 0 :
      return "Unit";
    case 1 :
      return "Renamed";
    case 2 :
      return "Two";
    case 3 :
      return {
        TAG: "Single",
        _0: next(2001) - 1000 | 0
      };
    case 4 :
      return {
        TAG: "Float",
        _0: (next(2001) - 1000 | 0) / 4
      };
    case 5 :
      return {
        TAG: "Pair",
        _0: string(),
        _1: next(2) === 0
      };
    case 6 :
      return {
        TAG: "Rec",
        a: string(),
        b: next(2) === 0 ? undefined : next(2001) - 1000 | 0
      };
    case 7 :
      return {
        TAG: "Opt",
        _0: next(2) === 0 ? undefined : next(2001) - 1000 | 0
      };
    case 8 :
      return {
        TAG: "List",
        _0: Stdlib_Array.fromInitializer(next(4), param => next(2001) - 1000 | 0)
      };
    case 9 :
      return {
        TAG: "Map",
        _0: Object.fromEntries(Stdlib_Array.fromInitializer(next(3), param => [
          string(),
          next(2001) - 1000 | 0
        ]))
      };
    case 10 :
      return {
        TAG: "Point",
        _0: {
          x: next(2001) - 1000 | 0,
          y: next(2001) - 1000 | 0
        }
      };
    default:
      return {
        TAG: "Nested",
        _0: ext(depth + 1 | 0)
      };
  }
}

function tree(depth) {
  if (depth > 4 || next(3) === 0) {
    return "Leaf";
  } else {
    return {
      TAG: "Node",
      left: tree(depth + 1 | 0),
      right: tree(depth + 1 | 0),
      value: next(2001) - 1000 | 0
    };
  }
}

function check(t, name, values, encode, decode, legacyEncode) {
  t.test(name, async t => {
    let failures = values.filter(v => {
      let json = encode(v);
      if (Primitive_object.notequal(Stdlib_Result.map(decode(json), encode), {
          TAG: "Ok",
          _0: json
        })) {
        return true;
      } else {
        return Primitive_object.notequal(Stdlib_Result.map(decode(legacyEncode(v)), encode), {
          TAG: "Ok",
          _0: json
        });
      }
    });
    t.equal(failures, [], name);
  });
}

Zora.test("@spice.serde random round trips", t => {
  let exts = Stdlib_Array.fromInitializer(500, param => ext(0));
  let trees = Stdlib_Array.fromInitializer(200, param => tree(0));
  check(t, "ext", exts, SerdeRust.ext_encode, SerdeRust.ext_decode, SerdeLegacy.ext_encode);
  check(t, "tree", trees, SerdeRust.tree_encode, SerdeRust.tree_decode, SerdeLegacy.tree_encode);
  t.test("generated every ext constructor", async t => {
    let tags = exts.map(v => v.TAG);
    t.equal(new Set(tags.map(tag => Stdlib_Option.getOr((tag == null) ? undefined : Primitive_option.some(tag), "unit"))).size, 10, "distinct payload constructors plus units");
  });
});

export {
  seed,
  next,
  int,
  string,
  ext,
  tree,
  check,
}
/*  Not a pure module */
