// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as Serde from "../../../src/Serde.mjs";
import * as Stdlib_Result from "@rescript/runtime/lib/es6/Stdlib_Result.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function testEqual(t, name, lhs, rhs) {
  t.test(name, async t => {
    t.equal(lhs, rhs, name);
  });
}

function json(prim0, prim1) {
  return JSON.parse(prim0, prim1 !== undefined ? Primitive_option.valFromOption(prim1) : undefined);
}

function isError(result) {
  return result.TAG !== "Ok";
}

Zora.test("@spice.serde polymorphic variants", t => {
  testEqual(t, "encode unit", Serde.poly_encode("Left"), JSON.parse(`"Left"`));
  testEqual(t, "encode renamed", Serde.size_encode("L"), JSON.parse(`"large"`));
  testEqual(t, "encode payload", Serde.poly_encode({
    NAME: "Payload",
    VAL: 1
  }), JSON.parse(`{"Payload":1}`));
  testEqual(t, "encode tuple", Serde.poly_encode({
    NAME: "Pair",
    VAL: [
      "a",
      true
    ]
  }), JSON.parse(`{"Pair":["a",true]}`));
  testEqual(t, "decode unit", Serde.poly_decode(JSON.parse(`"Right"`)), {
    TAG: "Ok",
    _0: "Right"
  });
  testEqual(t, "decode renamed", Serde.size_decode(JSON.parse(`"large"`)), {
    TAG: "Ok",
    _0: "L"
  });
  testEqual(t, "decode payload", Serde.poly_decode(JSON.parse(`{"Payload":2}`)), {
    TAG: "Ok",
    _0: {
      NAME: "Payload",
      VAL: 2
    }
  });
  testEqual(t, "decode tuple", Serde.poly_decode(JSON.parse(`{"Pair":["b",false]}`)), {
    TAG: "Ok",
    _0: {
      NAME: "Pair",
      VAL: [
        "b",
        false
      ]
    }
  });
  testEqual(t, "decode legacy unit", Serde.poly_decode(JSON.parse(`["Left"]`)), {
    TAG: "Ok",
    _0: "Left"
  });
  testEqual(t, "decode legacy payload", Serde.poly_decode(JSON.parse(`["Payload",3]`)), {
    TAG: "Ok",
    _0: {
      NAME: "Payload",
      VAL: 3
    }
  });
  testEqual(t, "unknown name fails", isError(Serde.poly_decode(JSON.parse(`"Up"`))), true);
});

Zora.test("@spice.serde externally tagged variants", t => {
  testEqual(t, "encode unit", Serde.external__encode("Unit"), JSON.parse(`"Unit"`));
  testEqual(t, "encode renamed", Serde.external__encode("Renamed"), JSON.parse(`"renamed"`));
  testEqual(t, "encode single", Serde.external__encode({
    TAG: "Single",
    _0: 1
  }), JSON.parse(`{"Single":1}`));
  testEqual(t, "encode tuple", Serde.external__encode({
    TAG: "Pair",
    _0: "a",
    _1: true
  }), JSON.parse(`{"Pair":["a",true]}`));
  testEqual(t, "encode record", Serde.external__encode({
    TAG: "Rec",
    a: "x",
    b: undefined
  }), JSON.parse(`{"Rec":{"a":"x"}}`));
  testEqual(t, "decode unit", Serde.external__decode(JSON.parse(`"Unit"`)), {
    TAG: "Ok",
    _0: "Unit"
  });
  testEqual(t, "decode renamed", Serde.external__decode(JSON.parse(`"renamed"`)), {
    TAG: "Ok",
    _0: "Renamed"
  });
  testEqual(t, "decode single", Serde.external__decode(JSON.parse(`{"Single":1}`)), {
    TAG: "Ok",
    _0: {
      TAG: "Single",
      _0: 1
    }
  });
  testEqual(t, "decode tuple", Serde.external__decode(JSON.parse(`{"Pair":["a",true]}`)), {
    TAG: "Ok",
    _0: {
      TAG: "Pair",
      _0: "a",
      _1: true
    }
  });
  testEqual(t, "decode record", Serde.external__decode(JSON.parse(`{"Rec":{"a":"x","b":2}}`)), {
    TAG: "Ok",
    _0: {
      TAG: "Rec",
      a: "x",
      b: 2
    }
  });
  testEqual(t, "decode legacy unit", Serde.external__decode(JSON.parse(`["Unit"]`)), {
    TAG: "Ok",
    _0: "Unit"
  });
  testEqual(t, "decode legacy tuple", Serde.external__decode(JSON.parse(`["Pair","a",true]`)), {
    TAG: "Ok",
    _0: {
      TAG: "Pair",
      _0: "a",
      _1: true
    }
  });
  testEqual(t, "decode legacy record", Serde.external__decode(JSON.parse(`["Rec",{"a":"x"}]`)), {
    TAG: "Ok",
    _0: {
      TAG: "Rec",
      a: "x",
      b: undefined
    }
  });
  testEqual(t, "payload errors carry the constructor in the path", Stdlib_Result.mapError(Serde.external__decode(JSON.parse(`{"Single":"no"}`)), e => e.path), {
    TAG: "Error",
    _0: ".Single"
  });
  testEqual(t, "two keys fail", isError(Serde.external__decode(JSON.parse(`{"Single":1,"Unit":2}`))), true);
  testEqual(t, "wrong tuple length fails", isError(Serde.external__decode(JSON.parse(`{"Pair":["a"]}`))), true);
  testEqual(t, "a unit name with an object fails", isError(Serde.external__decode(JSON.parse(`{"Unit":1}`))), true);
});

Zora.test("@spice.serde internally tagged variants (@tag)", t => {
  testEqual(t, "encode unit", Serde.internal_encode("Regular"), JSON.parse(`{"type":"Regular"}`));
  testEqual(t, "encode record", Serde.internal_encode({
    type: "Overlap",
    cameraSize: "M"
  }), JSON.parse(`{"type":"Overlap","cameraSize":"M"}`));
  testEqual(t, "encode renamed with field keys", Serde.internal_encode({
    type: "Full",
    screenFit: "cover",
    punchIn: true
  }), JSON.parse(`{"type":"full","screenFit":"cover","punch_in":true}`));
  testEqual(t, "encode nested", Serde.nested_encode({
    kind: "SideBySide",
    position: "Left",
    style: "Regular"
  }), JSON.parse(`{"kind":"SideBySide","position":"Left","style":{"type":"Regular"}}`));
  testEqual(t, "decode unit", Serde.internal_decode(JSON.parse(`{"type":"Regular"}`)), {
    TAG: "Ok",
    _0: "Regular"
  });
  testEqual(t, "decode record in any key order", Serde.internal_decode(JSON.parse(`{"cameraSize":"large","type":"Overlap"}`)), {
    TAG: "Ok",
    _0: {
      type: "Overlap",
      cameraSize: "L"
    }
  });
  testEqual(t, "decode renamed", Serde.internal_decode(JSON.parse(`{"type":"full","screenFit":"cover","punch_in":false}`)), {
    TAG: "Ok",
    _0: {
      type: "Full",
      screenFit: "cover",
      punchIn: false
    }
  });
  testEqual(t, "decode a bare unit name", Serde.internal_decode(JSON.parse(`"Regular"`)), {
    TAG: "Ok",
    _0: "Regular"
  });
  testEqual(t, "decode legacy record", Serde.internal_decode(JSON.parse(`["Overlap",{"cameraSize":["S"]}]`)), {
    TAG: "Ok",
    _0: {
      type: "Overlap",
      cameraSize: "S"
    }
  });
  testEqual(t, "decode nested legacy", Serde.nested_decode(JSON.parse(`["SideBySide",{"position":["Payload",1],"style":["Regular"]}]`)), {
    TAG: "Ok",
    _0: {
      kind: "SideBySide",
      position: {
        NAME: "Payload",
        VAL: 1
      },
      style: "Regular"
    }
  });
  testEqual(t, "field errors keep their path", Stdlib_Result.mapError(Serde.internal_decode(JSON.parse(`{"type":"Overlap","cameraSize":"XL"}`)), e => e.path), {
    TAG: "Error",
    _0: ".cameraSize"
  });
  testEqual(t, "missing tag fails", isError(Serde.internal_decode(JSON.parse(`{"cameraSize":"S"}`))), true);
  testEqual(t, "unknown tag fails", isError(Serde.internal_decode(JSON.parse(`{"type":"Other"}`))), true);
});

export {
  testEqual,
  json,
  isError,
}
/*  Not a pure module */
