// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dicts_test from "./spec/dicts_test.mjs";
import * as Serde_test from "./spec/serde_test.mjs";
import * as Arrays_test from "./spec/arrays_test.mjs";
import * as Tuples_test from "./spec/tuples_test.mjs";
import * as Records_test from "./spec/records_test.mjs";
import * as Results_test from "./spec/results_test.mjs";
import * as Variants_test from "./spec/variants_test.mjs";
import * as Serde_edge_test from "./spec/serde_edge_test.mjs";
import * as Serde_rust_test from "./spec/serde_rust_test.mjs";
import * as Polyvariants_test from "./spec/polyvariants_test.mjs";
import * as Serde_random_test from "./spec/serde_random_test.mjs";
import * as Encode_decode_test from "./spec/encode_decode_test.mjs";
import * as Raising_field_test from "./spec/raising_field_test.mjs";
import * as Top_level_options_test from "./spec/top_level_options_test.mjs";
import * as Generic_type_params_test from "./spec/generic_type_params_test.mjs";
import * as Optional_field_records_test from "./spec/optional_field_records_test.mjs";

let dataObject = Generic_type_params_test.dataObject;

let dataObjectJson = Generic_type_params_test.dataObjectJson;

let pairObject = Generic_type_params_test.pairObject;

let pairObjectJson = Generic_type_params_test.pairObjectJson;

let nestedObject = Generic_type_params_test.nestedObject;

let nestedObjectJson = Generic_type_params_test.nestedObjectJson;

let deepEqualWithBigInt = Records_test.deepEqualWithBigInt;

let optionRecord = Top_level_options_test.optionRecord;

let optionRecordJson = Top_level_options_test.optionRecordJson;

let nestedTuple = Top_level_options_test.nestedTuple;

let nestedTupleJson = Top_level_options_test.nestedTupleJson;

let payloadVariantJson = Top_level_options_test.payloadVariantJson;

let isError = Serde_test.isError;

let golden = Serde_rust_test.golden;

let used = Serde_rust_test.used;

let testEqual = Serde_edge_test.testEqual;

let json = Serde_edge_test.json;

let errorAt = Serde_edge_test.errorAt;

let roundTrips = Serde_edge_test.roundTrips;

let seed = Serde_random_test.seed;

let next = Serde_random_test.next;

let int = Serde_random_test.int;

let string = Serde_random_test.string;

let ext = Serde_random_test.ext;

let tree = Serde_random_test.tree;

let check = Serde_random_test.check;

export {
  dataObject,
  dataObjectJson,
  pairObject,
  pairObjectJson,
  nestedObject,
  nestedObjectJson,
  deepEqualWithBigInt,
  optionRecord,
  optionRecordJson,
  nestedTuple,
  nestedTupleJson,
  payloadVariantJson,
  isError,
  golden,
  used,
  testEqual,
  json,
  errorAt,
  roundTrips,
  seed,
  next,
  int,
  string,
  ext,
  tree,
  check,
}
/* Dicts_test Not a pure module */
