// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function stringDict_encode(v) {
  return Spice.dictToJson(Spice.stringToJson, v);
}

function stringDict_encodeJson(v) {
  return Spice.dictToJson(Spice.stringToJson, v);
}

function stringDict_decode(v) {
  return Spice.dictFromJson(Spice.stringFromJson, v);
}

function intDict_encode(v) {
  return Spice.dictToJson(Spice.intToJson, v);
}

function intDict_encodeJson(v) {
  return Spice.dictToJson(Spice.intToJson, v);
}

function intDict_decode(v) {
  return Spice.dictFromJson(Spice.intFromJson, v);
}

function inner_encode(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "id",
      Spice.intToJson(v.id)
    ],
    [
      "name",
      Spice.stringToJson(v.name)
    ]
  ]));
}

function inner_encodeJson(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "id",
      Spice.intToJson(v.id)
    ],
    [
      "name",
      Spice.stringToJson(v.name)
    ]
  ]));
}

function inner_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let spice_field_id = Stdlib_Option.getOr(Stdlib_Option.map(v["id"], Spice.intFromJson), Spice.error(undefined, "id" + " missing", v));
  if (spice_field_id.TAG === "Ok") {
    let spice_field_name = Stdlib_Option.getOr(Stdlib_Option.map(v["name"], Spice.stringFromJson), Spice.error(undefined, "name" + " missing", v));
    if (spice_field_name.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          id: spice_field_id._0,
          name: spice_field_name._0
        }
      };
    }
    let e = spice_field_name._0;
    return Spice.error("." + ("name" + e.path), e.message, e.value);
  }
  let e$1 = spice_field_id._0;
  return Spice.error("." + ("id" + e$1.path), e$1.message, e$1.value);
}

function innerDict_encode(v) {
  return Spice.dictToJson(inner_encodeJson, v);
}

function innerDict_encodeJson(v) {
  return Spice.dictToJson(inner_encodeJson, v);
}

function innerDict_decode(v) {
  return Spice.dictFromJson(inner_decode, v);
}

function dictT_encode(v) {
  return Spice.dictToJson(Spice.stringToJson, v);
}

function dictT_encodeJson(v) {
  return Spice.dictToJson(Spice.stringToJson, v);
}

function dictT_decode(v) {
  return Spice.dictFromJson(Spice.stringFromJson, v);
}

function optionStringDict_encode(v) {
  return Spice.dictOptionalToJson(extra => Spice.optionToJson(Spice.stringToJson, extra), v);
}

function optionStringDict_encodeJson(v) {
  return Spice.dictOptionalToJson(extra => Spice.optionToJson(Spice.stringToJson, extra), v);
}

function optionStringDict_decode(v) {
  return Spice.dictFromJson(extra => Spice.optionFromJson(Spice.stringFromJson, extra), v);
}

export {
  stringDict_encode,
  stringDict_encodeJson,
  stringDict_decode,
  intDict_encode,
  intDict_encodeJson,
  intDict_decode,
  inner_encode,
  inner_encodeJson,
  inner_decode,
  innerDict_encode,
  innerDict_encodeJson,
  innerDict_decode,
  dictT_encode,
  dictT_encodeJson,
  dictT_decode,
  optionStringDict_encode,
  optionStringDict_encodeJson,
  optionStringDict_decode,
}
/* No side effect */
