// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function te_encode(v) {
  let extra = v.nickname;
  return Object.fromEntries(Spice.filterOptional([
    [
      "name",
      Spice.stringToJson(v.name)
    ],
    [
      "nickname",
      Spice.optionToJson(Spice.stringToJson, extra)
    ]
  ]));
}

function te_encodeJson(v) {
  let extra = v.nickname;
  return Object.fromEntries(Spice.filterOptional([
    [
      "name",
      Spice.stringToJson(v.name)
    ],
    [
      "nickname",
      Spice.optionToJson(Spice.stringToJson, extra)
    ]
  ]));
}

function td_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let spice_field_name = Stdlib_Option.getOr(Stdlib_Option.map(v["name"], Spice.stringFromJson), Spice.error(undefined, "name" + " missing", v));
  if (spice_field_name.TAG === "Ok") {
    let spice_field_nickname = Stdlib_Option.getOr(Stdlib_Option.map(v["nickname"], extra => Spice.optionalFieldFromJson(Spice.stringFromJson, extra)), {
      TAG: "Ok",
      _0: undefined
    });
    if (spice_field_nickname.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          name: spice_field_name._0,
          nickname: spice_field_nickname._0
        }
      };
    }
    let e = spice_field_nickname._0;
    return Spice.error("." + ("nickname" + e.path), e.message, e.value);
  }
  let e$1 = spice_field_name._0;
  return Spice.error("." + ("name" + e$1.path), e$1.message, e$1.value);
}

export {
  te_encode,
  te_encodeJson,
  td_decode,
}
/* No side effect */
