// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function dataObject_encode(encoder_data) {
  return v => (Object.fromEntries(Spice.filterOptional([[
      "properties",
      Spice.arrayToJson(encoder_data, v.properties)
    ]])));
}

function dataObject_encodeJson(encoder_data) {
  return v => (Object.fromEntries(Spice.filterOptional([[
      "properties",
      Spice.arrayToJson(encoder_data, v.properties)
    ]])));
}

function dataObject_decode(decoder_data) {
  return v => {
    if (typeof v !== "object" || v === null || Array.isArray(v)) {
      return Spice.error(undefined, "Not an object", v);
    }
    let spice_field_properties = Stdlib_Option.getOr(Stdlib_Option.map(v["properties"], extra => Spice.arrayFromJson(decoder_data, extra)), Spice.error(undefined, "properties" + " missing", v));
    if (spice_field_properties.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          properties: spice_field_properties._0
        }
      };
    }
    let e = spice_field_properties._0;
    return Spice.error("." + ("properties" + e.path), e.message, e.value);
  };
}

function pairObject_encode(encoder_left) {
  return encoder_right => (v => (Object.fromEntries(Spice.filterOptional([
    [
      "left",
      encoder_left(v.left)
    ],
    [
      "right",
      encoder_right(v.right)
    ]
  ]))));
}

function pairObject_encodeJson(encoder_left) {
  return encoder_right => (v => (Object.fromEntries(Spice.filterOptional([
    [
      "left",
      encoder_left(v.left)
    ],
    [
      "right",
      encoder_right(v.right)
    ]
  ]))));
}

function pairObject_decode(decoder_left) {
  return decoder_right => (v => {
    if (typeof v !== "object" || v === null || Array.isArray(v)) {
      return Spice.error(undefined, "Not an object", v);
    }
    let spice_field_left = Stdlib_Option.getOr(Stdlib_Option.map(v["left"], decoder_left), Spice.error(undefined, "left" + " missing", v));
    if (spice_field_left.TAG === "Ok") {
      let spice_field_right = Stdlib_Option.getOr(Stdlib_Option.map(v["right"], decoder_right), Spice.error(undefined, "right" + " missing", v));
      if (spice_field_right.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: {
            left: spice_field_left._0,
            right: spice_field_right._0
          }
        };
      }
      let e = spice_field_right._0;
      return Spice.error("." + ("right" + e.path), e.message, e.value);
    }
    let e$1 = spice_field_left._0;
    return Spice.error("." + ("left" + e$1.path), e$1.message, e$1.value);
  });
}

function nestedObject_encode(encoder_data) {
  return v => {
    let extra = v.items;
    return Object.fromEntries(Spice.filterOptional([
      [
        "items",
        Spice.arrayToJson(dataObject_encodeJson(encoder_data), extra)
      ],
      [
        "selected",
        Spice.optionToJson(encoder_data, v.selected)
      ]
    ]));
  };
}

function nestedObject_encodeJson(encoder_data) {
  return v => {
    let extra = v.items;
    return Object.fromEntries(Spice.filterOptional([
      [
        "items",
        Spice.arrayToJson(dataObject_encodeJson(encoder_data), extra)
      ],
      [
        "selected",
        Spice.optionToJson(encoder_data, v.selected)
      ]
    ]));
  };
}

function nestedObject_decode(decoder_data) {
  return v => {
    if (typeof v !== "object" || v === null || Array.isArray(v)) {
      return Spice.error(undefined, "Not an object", v);
    }
    let spice_field_items = Stdlib_Option.getOr(Stdlib_Option.map(v["items"], extra => Spice.arrayFromJson(dataObject_decode(decoder_data), extra)), Spice.error(undefined, "items" + " missing", v));
    if (spice_field_items.TAG === "Ok") {
      let spice_field_selected = Stdlib_Option.getOr(Stdlib_Option.map(v["selected"], extra => Spice.optionalFieldFromJson(decoder_data, extra)), {
        TAG: "Ok",
        _0: undefined
      });
      if (spice_field_selected.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: {
            items: spice_field_items._0,
            selected: spice_field_selected._0
          }
        };
      }
      let e = spice_field_selected._0;
      return Spice.error("." + ("selected" + e.path), e.message, e.value);
    }
    let e$1 = spice_field_items._0;
    return Spice.error("." + ("items" + e$1.path), e$1.message, e$1.value);
  };
}

export {
  dataObject_encode,
  dataObject_encodeJson,
  dataObject_decode,
  pairObject_encode,
  pairObject_encodeJson,
  pairObject_decode,
  nestedObject_encode,
  nestedObject_encodeJson,
  nestedObject_decode,
}
/* No side effect */
