// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let DecodeError = /* @__PURE__ */Primitive_exceptions.create("RaisingField.RaisingCodec.DecodeError");

function t_encode(v) {
  return v;
}

function t_decode(json) {
  if (typeof json === "string") {
    return {
      TAG: "Ok",
      _0: json
    };
  }
  throw {
    RE_EXN_ID: DecodeError,
    _1: "Expected string",
    Error: new Error()
  };
}

let RaisingCodec = {
  DecodeError: DecodeError,
  t_encode: t_encode,
  t_encodeJson: t_encode,
  t_decode: t_decode
};

function t_encode$1(v) {
  let extra = v.label;
  let extra$1 = v.value;
  return Object.fromEntries(Spice.filterOptional([
    [
      "label",
      Spice.optionToJson(t_encode, extra)
    ],
    [
      "value",
      Spice.optionToJson(t_encode, extra$1)
    ]
  ]));
}

function t_encodeJson(v) {
  let extra = v.label;
  let extra$1 = v.value;
  return Object.fromEntries(Spice.filterOptional([
    [
      "label",
      Spice.optionToJson(t_encode, extra)
    ],
    [
      "value",
      Spice.optionToJson(t_encode, extra$1)
    ]
  ]));
}

function t_decode$1(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let label = Stdlib_Option.getOr(Stdlib_Option.map(v["label"], extra => Spice.optionalFieldFromJson(t_decode, extra)), {
    TAG: "Ok",
    _0: undefined
  });
  if (label.TAG === "Ok") {
    let value = Stdlib_Option.getOr(Stdlib_Option.map(v["value"], extra => Spice.optionalFieldFromJson(t_decode, extra)), {
      TAG: "Ok",
      _0: undefined
    });
    if (value.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          label: label._0,
          value: value._0
        }
      };
    }
    let e = value._0;
    return Spice.error("." + ("value" + e.path), e.message, e.value);
  }
  let e$1 = label._0;
  return Spice.error("." + ("label" + e$1.path), e$1.message, e$1.value);
}

export {
  RaisingCodec,
  t_encode$1 as t_encode,
  t_encodeJson,
  t_decode$1 as t_decode,
}
/* No side effect */
