// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function t_encode(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "spice-label",
      Spice.stringToJson(v.label)
    ],
    [
      "spice-value",
      Spice.intToJson(v.value)
    ]
  ]));
}

function t_encodeJson(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "spice-label",
      Spice.stringToJson(v.label)
    ],
    [
      "spice-value",
      Spice.intToJson(v.value)
    ]
  ]));
}

function t_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let spice_field_label = Stdlib_Option.getOr(Stdlib_Option.map(v["spice-label"], Spice.stringFromJson), Spice.error(undefined, "spice-label" + " missing", v));
  if (spice_field_label.TAG === "Ok") {
    let spice_field_value = Stdlib_Option.getOr(Stdlib_Option.map(v["spice-value"], Spice.intFromJson), Spice.error(undefined, "spice-value" + " missing", v));
    if (spice_field_value.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          label: spice_field_label._0,
          value: spice_field_value._0
        }
      };
    }
    let e = spice_field_value._0;
    return Spice.error("." + ("spice-value" + e.path), e.message, e.value);
  }
  let e$1 = spice_field_label._0;
  return Spice.error("." + ("spice-label" + e$1.path), e$1.message, e$1.value);
}

function t1_encode(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "label",
      Spice.stringToJson(v.label)
    ],
    [
      "value",
      Spice.intToJson(v.value)
    ]
  ]));
}

function t1_encodeJson(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "label",
      Spice.stringToJson(v.label)
    ],
    [
      "value",
      Spice.intToJson(v.value)
    ]
  ]));
}

function t1_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let spice_field_label = Stdlib_Option.getOr(Stdlib_Option.map(v["label"], Spice.stringFromJson), Spice.error(undefined, "label" + " missing", v));
  if (spice_field_label.TAG === "Ok") {
    let spice_field_value = Stdlib_Option.getOr(Stdlib_Option.map(v["value"], Spice.intFromJson), Spice.error(undefined, "value" + " missing", v));
    if (spice_field_value.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          label: spice_field_label._0,
          value: spice_field_value._0
        }
      };
    }
    let e = spice_field_value._0;
    return Spice.error("." + ("value" + e.path), e.message, e.value);
  }
  let e$1 = spice_field_label._0;
  return Spice.error("." + ("label" + e$1.path), e$1.message, e$1.value);
}

function tOp_encode(v) {
  let extra = v.label;
  let extra$1 = v.value;
  return Object.fromEntries(Spice.filterOptional([
    [
      "label",
      Spice.optionToJson(Spice.stringToJson, extra)
    ],
    [
      "value",
      Spice.optionToJson(Spice.intToJson, extra$1)
    ]
  ]));
}

function tOp_encodeJson(v) {
  let extra = v.label;
  let extra$1 = v.value;
  return Object.fromEntries(Spice.filterOptional([
    [
      "label",
      Spice.optionToJson(Spice.stringToJson, extra)
    ],
    [
      "value",
      Spice.optionToJson(Spice.intToJson, extra$1)
    ]
  ]));
}

function tOp_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let spice_field_label = Stdlib_Option.getOr(Stdlib_Option.map(v["label"], extra => Spice.optionalFieldFromJson(Spice.stringFromJson, extra)), {
    TAG: "Ok",
    _0: undefined
  });
  if (spice_field_label.TAG === "Ok") {
    let spice_field_value = Stdlib_Option.getOr(Stdlib_Option.map(v["value"], extra => Spice.optionalFieldFromJson(Spice.intFromJson, extra)), {
      TAG: "Ok",
      _0: undefined
    });
    if (spice_field_value.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          label: spice_field_label._0,
          value: spice_field_value._0
        }
      };
    }
    let e = spice_field_value._0;
    return Spice.error("." + ("value" + e.path), e.message, e.value);
  }
  let e$1 = spice_field_label._0;
  return Spice.error("." + ("label" + e$1.path), e$1.message, e$1.value);
}

function t2_encode(v) {
  let extra = v.o;
  let extra$1 = v.n;
  let extra$2 = v.on;
  let extra$3 = v.n2;
  return Object.fromEntries(Spice.filterOptional([
    [
      "o",
      Spice.optionToJson(Spice.stringToJson, extra)
    ],
    [
      "n",
      Spice.nullToJson(Spice.stringToJson, extra$1)
    ],
    [
      "on",
      Spice.optionToJson(extra => Spice.nullToJson(Spice.stringToJson, extra), extra$2)
    ],
    [
      "n2",
      Spice.nullToJson(Spice.stringToJson, extra$3)
    ]
  ]));
}

function t2_encodeJson(v) {
  let extra = v.o;
  let extra$1 = v.n;
  let extra$2 = v.on;
  let extra$3 = v.n2;
  return Object.fromEntries(Spice.filterOptional([
    [
      "o",
      Spice.optionToJson(Spice.stringToJson, extra)
    ],
    [
      "n",
      Spice.nullToJson(Spice.stringToJson, extra$1)
    ],
    [
      "on",
      Spice.optionToJson(extra => Spice.nullToJson(Spice.stringToJson, extra), extra$2)
    ],
    [
      "n2",
      Spice.nullToJson(Spice.stringToJson, extra$3)
    ]
  ]));
}

function t2_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let spice_field_o = Stdlib_Option.getOr(Stdlib_Option.map(v["o"], extra => Spice.optionalFieldFromJson(Spice.stringFromJson, extra)), {
    TAG: "Ok",
    _0: undefined
  });
  if (spice_field_o.TAG === "Ok") {
    let spice_field_n = Stdlib_Option.getOr(Stdlib_Option.map(v["n"], extra => Spice.nullFromJson(Spice.stringFromJson, extra)), Spice.error(undefined, "n" + " missing", v));
    if (spice_field_n.TAG === "Ok") {
      let spice_field_on = Stdlib_Option.getOr(Stdlib_Option.map(v["on"], extra => Spice.optionalFieldFromJson(extra => Spice.nullFromJson(Spice.stringFromJson, extra), extra)), {
        TAG: "Ok",
        _0: undefined
      });
      if (spice_field_on.TAG === "Ok") {
        let spice_field_n2 = Stdlib_Option.getOr(Stdlib_Option.map(v["n2"], extra => Spice.nullFromJson(Spice.stringFromJson, extra)), Spice.error(undefined, "n2" + " missing", v));
        if (spice_field_n2.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              o: spice_field_o._0,
              n: spice_field_n._0,
              on: spice_field_on._0,
              n2: spice_field_n2._0
            }
          };
        }
        let e = spice_field_n2._0;
        return Spice.error("." + ("n2" + e.path), e.message, e.value);
      }
      let e$1 = spice_field_on._0;
      return Spice.error("." + ("on" + e$1.path), e$1.message, e$1.value);
    }
    let e$2 = spice_field_n._0;
    return Spice.error("." + ("n" + e$2.path), e$2.message, e$2.value);
  }
  let e$3 = spice_field_o._0;
  return Spice.error("." + ("o" + e$3.path), e$3.message, e$3.value);
}

function t3_encode(v) {
  let extra = v.value2;
  return Object.fromEntries(Spice.filterOptional([
    [
      "value",
      Spice.intToJson(v.value)
    ],
    [
      "value2",
      Spice.optionToJson(Spice.intToJson, extra)
    ]
  ]));
}

function t3_encodeJson(v) {
  let extra = v.value2;
  return Object.fromEntries(Spice.filterOptional([
    [
      "value",
      Spice.intToJson(v.value)
    ],
    [
      "value2",
      Spice.optionToJson(Spice.intToJson, extra)
    ]
  ]));
}

function t3_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let spice_field_value = Stdlib_Option.getOr(Stdlib_Option.map(v["value"], Spice.intFromJson), {
    TAG: "Ok",
    _0: 0
  });
  if (spice_field_value.TAG === "Ok") {
    let spice_field_value2 = Stdlib_Option.getOr(Stdlib_Option.map(v["value2"], extra => Spice.optionalFieldFromJson(Spice.intFromJson, extra)), {
      TAG: "Ok",
      _0: 1
    });
    if (spice_field_value2.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          value: spice_field_value._0,
          value2: spice_field_value2._0
        }
      };
    }
    let e = spice_field_value2._0;
    return Spice.error("." + ("value2" + e.path), e.message, e.value);
  }
  let e$1 = spice_field_value._0;
  return Spice.error("." + ("value" + e$1.path), e$1.message, e$1.value);
}

function t4_encode(v) {
  let extra = v.b;
  let extra$1 = v.c;
  return Object.fromEntries(Spice.filterOptional([
    [
      "a",
      Spice.bigintToJson(v.a)
    ],
    [
      "b",
      Spice.optionToJson(Spice.bigintToJson, extra)
    ],
    [
      "c",
      Spice.optionToJson(Spice.bigintToJson, extra$1)
    ]
  ]));
}

function t4_encodeJson(v) {
  let extra = v.b;
  let extra$1 = v.c;
  return Object.fromEntries(Spice.filterOptional([
    [
      "a",
      Spice.bigintToJson(v.a)
    ],
    [
      "b",
      Spice.optionToJson(Spice.bigintToJson, extra)
    ],
    [
      "c",
      Spice.optionToJson(Spice.bigintToJson, extra$1)
    ]
  ]));
}

function t4_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let spice_field_a = Stdlib_Option.getOr(Stdlib_Option.map(v["a"], Spice.bigintFromJson), Spice.error(undefined, "a" + " missing", v));
  if (spice_field_a.TAG === "Ok") {
    let spice_field_b = Stdlib_Option.getOr(Stdlib_Option.map(v["b"], extra => Spice.optionalFieldFromJson(Spice.bigintFromJson, extra)), {
      TAG: "Ok",
      _0: undefined
    });
    if (spice_field_b.TAG === "Ok") {
      let spice_field_c = Stdlib_Option.getOr(Stdlib_Option.map(v["c"], extra => Spice.optionalFieldFromJson(Spice.bigintFromJson, extra)), {
        TAG: "Ok",
        _0: undefined
      });
      if (spice_field_c.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: {
            a: spice_field_a._0,
            b: spice_field_b._0,
            c: spice_field_c._0
          }
        };
      }
      let e = spice_field_c._0;
      return Spice.error("." + ("c" + e.path), e.message, e.value);
    }
    let e$1 = spice_field_b._0;
    return Spice.error("." + ("b" + e$1.path), e$1.message, e$1.value);
  }
  let e$2 = spice_field_a._0;
  return Spice.error("." + ("a" + e$2.path), e$2.message, e$2.value);
}

function t5_encode(v) {
  let extra = v.maybeNull;
  return Object.fromEntries(Spice.filterOptional([[
      "maybeNull",
      Spice.optionToJson(extra => Spice.nullToJson(Spice.stringToJson, extra), extra)
    ]]));
}

function t5_encodeJson(v) {
  let extra = v.maybeNull;
  return Object.fromEntries(Spice.filterOptional([[
      "maybeNull",
      Spice.optionToJson(extra => Spice.nullToJson(Spice.stringToJson, extra), extra)
    ]]));
}

function t5_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let spice_field_maybeNull = Stdlib_Option.getOr(Stdlib_Option.map(v["maybeNull"], extra => Spice.optionalFieldFromJson(extra => Spice.nullFromJson(Spice.stringFromJson, extra), extra)), {
    TAG: "Ok",
    _0: undefined
  });
  if (spice_field_maybeNull.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        maybeNull: spice_field_maybeNull._0
      }
    };
  }
  let e = spice_field_maybeNull._0;
  return Spice.error("." + ("maybeNull" + e.path), e.message, e.value);
}

function inner_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let spice_field_value = Stdlib_Option.getOr(Stdlib_Option.map(v["value"], Spice.intFromJson), Spice.error(undefined, "value" + " missing", v));
  if (spice_field_value.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        value: spice_field_value._0
      }
    };
  }
  let e = spice_field_value._0;
  return Spice.error("." + ("value" + e.path), e.message, e.value);
}

function outer_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let spice_field_one = Stdlib_Option.getOr(Stdlib_Option.map(v["one"], inner_decode), Spice.error(undefined, "one" + " missing", v));
  if (spice_field_one.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        one: spice_field_one._0
      }
    };
  }
  let e = spice_field_one._0;
  return Spice.error("." + ("one" + e.path), e.message, e.value);
}

function deeplyNested_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let spice_field_level1 = Stdlib_Option.getOr(Stdlib_Option.map(v["level1"], outer_decode), Spice.error(undefined, "level1" + " missing", v));
  if (spice_field_level1.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        level1: spice_field_level1._0
      }
    };
  }
  let e = spice_field_level1._0;
  return Spice.error("." + ("level1" + e.path), e.message, e.value);
}

export {
  t_encode,
  t_encodeJson,
  t_decode,
  t1_encode,
  t1_encodeJson,
  t1_decode,
  tOp_encode,
  tOp_encodeJson,
  tOp_decode,
  t2_encode,
  t2_encodeJson,
  t2_decode,
  t3_encode,
  t3_encodeJson,
  t3_decode,
  t4_encode,
  t4_encodeJson,
  t4_decode,
  t5_encode,
  t5_encodeJson,
  t5_decode,
  inner_decode,
  outer_decode,
  deeplyNested_decode,
}
/* No side effect */
