// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function point_encode(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "x",
      Spice.intToJson(v.x)
    ],
    [
      "y",
      Spice.intToJson(v.y)
    ]
  ]));
}

function point_encodeJson(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "x",
      Spice.intToJson(v.x)
    ],
    [
      "y",
      Spice.intToJson(v.y)
    ]
  ]));
}

function point_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let spice_field_x = Stdlib_Option.getOr(Stdlib_Option.map(v["x"], Spice.intFromJson), Spice.error(undefined, "x" + " missing", v));
  if (spice_field_x.TAG === "Ok") {
    let spice_field_y = Stdlib_Option.getOr(Stdlib_Option.map(v["y"], Spice.intFromJson), Spice.error(undefined, "y" + " missing", v));
    if (spice_field_y.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          x: spice_field_x._0,
          y: spice_field_y._0
        }
      };
    }
    let e = spice_field_y._0;
    return Spice.error("." + ("y" + e.path), e.message, e.value);
  }
  let e$1 = spice_field_x._0;
  return Spice.error("." + ("x" + e$1.path), e$1.message, e$1.value);
}

function ext_decode(v) {
  if (!Array.isArray(v)) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (v.length === 0) {
    return Spice.error(undefined, "Expected variant, found empty array", v);
  }
  let match = v[0];
  if (typeof match === "string") {
    switch (match) {
      case "Float" :
        if (v.length !== 2) {
          return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
        }
        let v0 = Spice.floatFromJson(v[1]);
        if (v0.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              TAG: "Float",
              _0: v0._0
            }
          };
        }
        let e = v0._0;
        return {
          TAG: "Error",
          _0: {
            path: "[1]" + e.path,
            message: e.message,
            value: e.value
          }
        };
      case "List" :
        if (v.length !== 2) {
          return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
        }
        let extra = v[1];
        let v0$1 = Spice.arrayFromJson(Spice.intFromJson, extra);
        if (v0$1.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              TAG: "List",
              _0: v0$1._0
            }
          };
        }
        let e$1 = v0$1._0;
        return {
          TAG: "Error",
          _0: {
            path: "[1]" + e$1.path,
            message: e$1.message,
            value: e$1.value
          }
        };
      case "Map" :
        if (v.length !== 2) {
          return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
        }
        let extra$1 = v[1];
        let v0$2 = Spice.dictFromJson(Spice.intFromJson, extra$1);
        if (v0$2.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              TAG: "Map",
              _0: v0$2._0
            }
          };
        }
        let e$2 = v0$2._0;
        return {
          TAG: "Error",
          _0: {
            path: "[1]" + e$2.path,
            message: e$2.message,
            value: e$2.value
          }
        };
      case "Nested" :
        if (v.length !== 2) {
          return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
        }
        let v0$3 = ext_decode(v[1]);
        if (v0$3.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              TAG: "Nested",
              _0: v0$3._0
            }
          };
        }
        let e$3 = v0$3._0;
        return {
          TAG: "Error",
          _0: {
            path: "[1]" + e$3.path,
            message: e$3.message,
            value: e$3.value
          }
        };
      case "Opt" :
        if (v.length !== 2) {
          return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
        }
        let extra$2 = v[1];
        let v0$4 = Spice.optionFromJson(Spice.intFromJson, extra$2);
        if (v0$4.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              TAG: "Opt",
              _0: v0$4._0
            }
          };
        }
        let e$4 = v0$4._0;
        return {
          TAG: "Error",
          _0: {
            path: "[1]" + e$4.path,
            message: e$4.message,
            value: e$4.value
          }
        };
      case "Pair" :
        if (v.length !== 3) {
          return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
        }
        let match$1 = Spice.stringFromJson(v[1]);
        let match$2 = Spice.boolFromJson(v[2]);
        if (match$1.TAG === "Ok") {
          if (match$2.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                TAG: "Pair",
                _0: match$1._0,
                _1: match$2._0
              }
            };
          }
          let e$5 = match$2._0;
          return {
            TAG: "Error",
            _0: {
              path: "[2]" + e$5.path,
              message: e$5.message,
              value: e$5.value
            }
          };
        }
        let e$6 = match$1._0;
        return {
          TAG: "Error",
          _0: {
            path: "[1]" + e$6.path,
            message: e$6.message,
            value: e$6.value
          }
        };
      case "Point" :
        if (v.length !== 2) {
          return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
        }
        let v0$5 = point_decode(v[1]);
        if (v0$5.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              TAG: "Point",
              _0: v0$5._0
            }
          };
        }
        let e$7 = v0$5._0;
        return {
          TAG: "Error",
          _0: {
            path: "[1]" + e$7.path,
            message: e$7.message,
            value: e$7.value
          }
        };
      case "Rec" :
        if (v.length !== 2) {
          return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
        }
        let v$1 = v[1];
        let v$2;
        if (typeof v$1 === "object" && v$1 !== null && !Array.isArray(v$1)) {
          let spice_field_a = Stdlib_Option.getOr(Stdlib_Option.map(v$1["a"], Spice.stringFromJson), Spice.error(undefined, "a" + " missing", v$1));
          if (spice_field_a.TAG === "Ok") {
            let spice_field_b = Stdlib_Option.getOr(Stdlib_Option.map(v$1["b"], extra => Spice.optionalFieldFromJson(Spice.intFromJson, extra)), {
              TAG: "Ok",
              _0: undefined
            });
            if (spice_field_b.TAG === "Ok") {
              v$2 = {
                TAG: "Ok",
                _0: {
                  TAG: "Rec",
                  a: spice_field_a._0,
                  b: spice_field_b._0
                }
              };
            } else {
              let e$8 = spice_field_b._0;
              v$2 = Spice.error("." + ("b" + e$8.path), e$8.message, e$8.value);
            }
          } else {
            let e$9 = spice_field_a._0;
            v$2 = Spice.error("." + ("a" + e$9.path), e$9.message, e$9.value);
          }
        } else {
          v$2 = Spice.error(undefined, "Not an object", v$1);
        }
        if (v$2.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$2._0
          };
        }
        let e$10 = v$2._0;
        return {
          TAG: "Error",
          _0: {
            path: "[1]" + e$10.path,
            message: e$10.message,
            value: e$10.value
          }
        };
      case "Renamed" :
        if (v.length !== 1) {
          return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
        } else {
          return {
            TAG: "Ok",
            _0: "Renamed"
          };
        }
      case "Single" :
        if (v.length !== 2) {
          return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
        }
        let v0$6 = Spice.intFromJson(v[1]);
        if (v0$6.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              TAG: "Single",
              _0: v0$6._0
            }
          };
        }
        let e$11 = v0$6._0;
        return {
          TAG: "Error",
          _0: {
            path: "[1]" + e$11.path,
            message: e$11.message,
            value: e$11.value
          }
        };
      case "Two" :
        if (v.length !== 1) {
          return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
        } else {
          return {
            TAG: "Ok",
            _0: "Two"
          };
        }
      case "Unit" :
        if (v.length !== 1) {
          return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
        } else {
          return {
            TAG: "Ok",
            _0: "Unit"
          };
        }
    }
  }
  return Spice.error(undefined, "Invalid variant constructor", v[0]);
}

function ext_encodeJson(v) {
  if (typeof v !== "object") {
    switch (v) {
      case "Unit" :
        return ["Unit"];
      case "Renamed" :
        return ["Renamed"];
      case "Two" :
        return ["Two"];
    }
  } else {
    switch (v.TAG) {
      case "Single" :
        return [
          "Single",
          Spice.intToJson(v._0)
        ];
      case "Float" :
        return [
          "Float",
          Spice.floatToJson(v._0)
        ];
      case "Pair" :
        return [
          "Pair",
          Spice.stringToJson(v._0),
          Spice.boolToJson(v._1)
        ];
      case "Rec" :
        return [
          "Rec",
          Object.fromEntries(Spice.filterOptional([
            [
              "a",
              Spice.stringToJson(v.a)
            ],
            [
              "b",
              Spice.optionToJson(Spice.intToJson, v.b)
            ]
          ]))
        ];
      case "Opt" :
        return [
          "Opt",
          Spice.optionToNullableJson(Spice.intToJson, v._0)
        ];
      case "List" :
        return [
          "List",
          Spice.arrayToJson(Spice.intToJson, v._0)
        ];
      case "Map" :
        return [
          "Map",
          Spice.dictToJson(Spice.intToJson, v._0)
        ];
      case "Nested" :
        return [
          "Nested",
          ext_encodeJson(v._0)
        ];
      case "Point" :
        return [
          "Point",
          point_encodeJson(v._0)
        ];
    }
  }
}

function ext_encode(v) {
  if (typeof v !== "object") {
    switch (v) {
      case "Unit" :
        return ["Unit"];
      case "Renamed" :
        return ["Renamed"];
      case "Two" :
        return ["Two"];
    }
  } else {
    switch (v.TAG) {
      case "Single" :
        return [
          "Single",
          Spice.intToJson(v._0)
        ];
      case "Float" :
        return [
          "Float",
          Spice.floatToJson(v._0)
        ];
      case "Pair" :
        return [
          "Pair",
          Spice.stringToJson(v._0),
          Spice.boolToJson(v._1)
        ];
      case "Rec" :
        return [
          "Rec",
          Object.fromEntries(Spice.filterOptional([
            [
              "a",
              Spice.stringToJson(v.a)
            ],
            [
              "b",
              Spice.optionToJson(Spice.intToJson, v.b)
            ]
          ]))
        ];
      case "Opt" :
        return [
          "Opt",
          Spice.optionToNullableJson(Spice.intToJson, v._0)
        ];
      case "List" :
        return [
          "List",
          Spice.arrayToJson(Spice.intToJson, v._0)
        ];
      case "Map" :
        return [
          "Map",
          Spice.dictToJson(Spice.intToJson, v._0)
        ];
      case "Nested" :
        return [
          "Nested",
          ext_encodeJson(v._0)
        ];
      case "Point" :
        return [
          "Point",
          point_encodeJson(v._0)
        ];
    }
  }
}

function tree_encodeJson(v) {
  if (typeof v !== "object") {
    return ["Leaf"];
  } else {
    return [
      "Node",
      Object.fromEntries(Spice.filterOptional([
        [
          "left",
          tree_encodeJson(v.left)
        ],
        [
          "right",
          tree_encodeJson(v.right)
        ],
        [
          "value",
          Spice.intToJson(v.value)
        ]
      ]))
    ];
  }
}

function tree_decode(v) {
  if (!Array.isArray(v)) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (v.length === 0) {
    return Spice.error(undefined, "Expected variant, found empty array", v);
  }
  let match = v[0];
  if (typeof match === "string") {
    switch (match) {
      case "Leaf" :
        if (v.length !== 1) {
          return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
        } else {
          return {
            TAG: "Ok",
            _0: "Leaf"
          };
        }
      case "Node" :
        if (v.length !== 2) {
          return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
        }
        let v$1 = v[1];
        let v$2;
        if (typeof v$1 === "object" && v$1 !== null && !Array.isArray(v$1)) {
          let spice_field_left = Stdlib_Option.getOr(Stdlib_Option.map(v$1["left"], tree_decode), Spice.error(undefined, "left" + " missing", v$1));
          if (spice_field_left.TAG === "Ok") {
            let spice_field_right = Stdlib_Option.getOr(Stdlib_Option.map(v$1["right"], tree_decode), Spice.error(undefined, "right" + " missing", v$1));
            if (spice_field_right.TAG === "Ok") {
              let spice_field_value = Stdlib_Option.getOr(Stdlib_Option.map(v$1["value"], Spice.intFromJson), Spice.error(undefined, "value" + " missing", v$1));
              if (spice_field_value.TAG === "Ok") {
                v$2 = {
                  TAG: "Ok",
                  _0: {
                    TAG: "Node",
                    left: spice_field_left._0,
                    right: spice_field_right._0,
                    value: spice_field_value._0
                  }
                };
              } else {
                let e = spice_field_value._0;
                v$2 = Spice.error("." + ("value" + e.path), e.message, e.value);
              }
            } else {
              let e$1 = spice_field_right._0;
              v$2 = Spice.error("." + ("right" + e$1.path), e$1.message, e$1.value);
            }
          } else {
            let e$2 = spice_field_left._0;
            v$2 = Spice.error("." + ("left" + e$2.path), e$2.message, e$2.value);
          }
        } else {
          v$2 = Spice.error(undefined, "Not an object", v$1);
        }
        if (v$2.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$2._0
          };
        }
        let e$3 = v$2._0;
        return {
          TAG: "Error",
          _0: {
            path: "[1]" + e$3.path,
            message: e$3.message,
            value: e$3.value
          }
        };
    }
  }
  return Spice.error(undefined, "Invalid variant constructor", v[0]);
}

function tree_encode(v) {
  if (typeof v !== "object") {
    return ["Leaf"];
  } else {
    return [
      "Node",
      Object.fromEntries(Spice.filterOptional([
        [
          "left",
          tree_encodeJson(v.left)
        ],
        [
          "right",
          tree_encodeJson(v.right)
        ],
        [
          "value",
          Spice.intToJson(v.value)
        ]
      ]))
    ];
  }
}

export {
  point_encode,
  point_encodeJson,
  point_decode,
  ext_encode,
  ext_encodeJson,
  ext_decode,
  tree_encode,
  tree_encodeJson,
  tree_decode,
}
/* No side effect */
