// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function size_encode(v) {
  if (v === "M") {
    return "M";
  } else if (v === "S") {
    return "S";
  } else {
    return "large";
  }
}

function size_encodeJson(v) {
  if (v === "M") {
    return "M";
  } else if (v === "S") {
    return "S";
  } else {
    return "large";
  }
}

function size_decode(v) {
  if (v === null) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (Array.isArray(v)) {
    if (v.length === 0) {
      return Spice.error(undefined, "Expected variant, found empty array", v);
    }
    let match = v[0];
    if (typeof match === "string") {
      switch (match) {
        case "L" :
          if (v.length !== 1) {
            return Spice.error(undefined, "Invalid number of arguments to polyvariant constructor", v);
          } else {
            return {
              TAG: "Ok",
              _0: "L"
            };
          }
        case "M" :
          if (v.length !== 1) {
            return Spice.error(undefined, "Invalid number of arguments to polyvariant constructor", v);
          } else {
            return {
              TAG: "Ok",
              _0: "M"
            };
          }
        case "S" :
          if (v.length !== 1) {
            return Spice.error(undefined, "Invalid number of arguments to polyvariant constructor", v);
          } else {
            return {
              TAG: "Ok",
              _0: "S"
            };
          }
      }
    }
    return Spice.error(undefined, "Invalid polymorphic variant constructor", v[0]);
  }
  switch (typeof v) {
    case "string" :
      if (v === "S") {
        return {
          TAG: "Ok",
          _0: "S"
        };
      } else if (v === "M") {
        return {
          TAG: "Ok",
          _0: "M"
        };
      } else if (v === "large") {
        return {
          TAG: "Ok",
          _0: "L"
        };
      } else {
        return Spice.error(undefined, "Invalid variant constructor", v);
      }
    case "boolean" :
    case "number" :
      return Spice.error(undefined, "Not a variant", v);
    case "object" :
      let match$1 = Object.entries(v);
      if (match$1.length !== 1) {
        return Spice.error(undefined, "Expected an object with one key", v);
      }
      let match$2 = match$1[0];
      let payload = match$2[1];
      let spice_tag = match$2[0];
      if (spice_tag === "S") {
        let v$1;
        v$1 = payload === null ? ({
            TAG: "Ok",
            _0: "S"
          }) : Spice.error(undefined, "Expected null", payload);
        if (v$1.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$1._0
          };
        }
        let e = v$1._0;
        return {
          TAG: "Error",
          _0: {
            path: ".S" + e.path,
            message: e.message,
            value: e.value
          }
        };
      }
      if (spice_tag === "M") {
        let v$2;
        v$2 = payload === null ? ({
            TAG: "Ok",
            _0: "M"
          }) : Spice.error(undefined, "Expected null", payload);
        if (v$2.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$2._0
          };
        }
        let e$1 = v$2._0;
        return {
          TAG: "Error",
          _0: {
            path: ".M" + e$1.path,
            message: e$1.message,
            value: e$1.value
          }
        };
      }
      if (spice_tag !== "large") {
        return Spice.error(undefined, "Invalid variant constructor", v);
      }
      let v$3;
      v$3 = payload === null ? ({
          TAG: "Ok",
          _0: "L"
        }) : Spice.error(undefined, "Expected null", payload);
      if (v$3.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: v$3._0
        };
      }
      let e$2 = v$3._0;
      return {
        TAG: "Error",
        _0: {
          path: ".large" + e$2.path,
          message: e$2.message,
          value: e$2.value
        }
      };
  }
}

function poly_encode(v) {
  if (typeof v !== "object") {
    if (v === "Left") {
      return "Left";
    } else {
      return "Right";
    }
  }
  if (v.NAME === "Payload") {
    return Object.fromEntries([[
        "Payload",
        Spice.intToJson(v.VAL)
      ]]);
  }
  let match = v.VAL;
  return Object.fromEntries([[
      "Pair",
      [
        Spice.stringToJson(match[0]),
        Spice.boolToJson(match[1])
      ]
    ]]);
}

function poly_encodeJson(v) {
  if (typeof v !== "object") {
    if (v === "Left") {
      return "Left";
    } else {
      return "Right";
    }
  }
  if (v.NAME === "Payload") {
    return Object.fromEntries([[
        "Payload",
        Spice.intToJson(v.VAL)
      ]]);
  }
  let match = v.VAL;
  return Object.fromEntries([[
      "Pair",
      [
        Spice.stringToJson(match[0]),
        Spice.boolToJson(match[1])
      ]
    ]]);
}

function poly_decode(v) {
  if (v === null) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (Array.isArray(v)) {
    if (v.length === 0) {
      return Spice.error(undefined, "Expected variant, found empty array", v);
    }
    let match = v[0];
    if (typeof match === "string") {
      switch (match) {
        case "Left" :
          if (v.length !== 1) {
            return Spice.error(undefined, "Invalid number of arguments to polyvariant constructor", v);
          } else {
            return {
              TAG: "Ok",
              _0: "Left"
            };
          }
        case "Pair" :
          if (v.length !== 3) {
            return Spice.error(undefined, "Invalid number of arguments to polyvariant constructor", v);
          }
          let match$1 = Spice.stringFromJson(v[1]);
          let match$2 = Spice.boolFromJson(v[2]);
          if (match$1.TAG === "Ok") {
            if (match$2.TAG === "Ok") {
              return {
                TAG: "Ok",
                _0: {
                  NAME: "Pair",
                  VAL: [
                    match$1._0,
                    match$2._0
                  ]
                }
              };
            }
            let e = match$2._0;
            return {
              TAG: "Error",
              _0: {
                path: "[2]" + e.path,
                message: e.message,
                value: e.value
              }
            };
          }
          let e$1 = match$1._0;
          return {
            TAG: "Error",
            _0: {
              path: "[1]" + e$1.path,
              message: e$1.message,
              value: e$1.value
            }
          };
        case "Payload" :
          if (v.length !== 2) {
            return Spice.error(undefined, "Invalid number of arguments to polyvariant constructor", v);
          }
          let v0 = Spice.intFromJson(v[1]);
          if (v0.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                NAME: "Payload",
                VAL: v0._0
              }
            };
          }
          let e$2 = v0._0;
          return {
            TAG: "Error",
            _0: {
              path: "[1]" + e$2.path,
              message: e$2.message,
              value: e$2.value
            }
          };
        case "Right" :
          if (v.length !== 1) {
            return Spice.error(undefined, "Invalid number of arguments to polyvariant constructor", v);
          } else {
            return {
              TAG: "Ok",
              _0: "Right"
            };
          }
      }
    }
    return Spice.error(undefined, "Invalid polymorphic variant constructor", v[0]);
  }
  switch (typeof v) {
    case "string" :
      if (v === "Left") {
        return {
          TAG: "Ok",
          _0: "Left"
        };
      } else if (v === "Right") {
        return {
          TAG: "Ok",
          _0: "Right"
        };
      } else {
        return Spice.error(undefined, "Invalid variant constructor", v);
      }
    case "boolean" :
    case "number" :
      return Spice.error(undefined, "Not a variant", v);
    case "object" :
      let match$3 = Object.entries(v);
      if (match$3.length !== 1) {
        return Spice.error(undefined, "Expected an object with one key", v);
      }
      let match$4 = match$3[0];
      let payload = match$4[1];
      let spice_tag = match$4[0];
      if (spice_tag === "Left") {
        let v$1;
        v$1 = payload === null ? ({
            TAG: "Ok",
            _0: "Left"
          }) : Spice.error(undefined, "Expected null", payload);
        if (v$1.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$1._0
          };
        }
        let e$3 = v$1._0;
        return {
          TAG: "Error",
          _0: {
            path: ".Left" + e$3.path,
            message: e$3.message,
            value: e$3.value
          }
        };
      }
      if (spice_tag === "Right") {
        let v$2;
        v$2 = payload === null ? ({
            TAG: "Ok",
            _0: "Right"
          }) : Spice.error(undefined, "Expected null", payload);
        if (v$2.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$2._0
          };
        }
        let e$4 = v$2._0;
        return {
          TAG: "Error",
          _0: {
            path: ".Right" + e$4.path,
            message: e$4.message,
            value: e$4.value
          }
        };
      }
      if (spice_tag === "Payload") {
        let v0$1 = Spice.intFromJson(payload);
        let v$3;
        v$3 = v0$1.TAG === "Ok" ? ({
            TAG: "Ok",
            _0: {
              NAME: "Payload",
              VAL: v0$1._0
            }
          }) : ({
            TAG: "Error",
            _0: v0$1._0
          });
        if (v$3.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$3._0
          };
        }
        let e$5 = v$3._0;
        return {
          TAG: "Error",
          _0: {
            path: ".Payload" + e$5.path,
            message: e$5.message,
            value: e$5.value
          }
        };
      }
      if (spice_tag !== "Pair") {
        return Spice.error(undefined, "Invalid variant constructor", v);
      }
      let v$4;
      if (Array.isArray(payload)) {
        if (payload.length !== 2) {
          v$4 = Spice.error(undefined, "Invalid number of arguments to variant constructor", payload);
        } else {
          let match$5 = Spice.stringFromJson(payload[0]);
          let match$6 = Spice.boolFromJson(payload[1]);
          if (match$5.TAG === "Ok") {
            if (match$6.TAG === "Ok") {
              v$4 = {
                TAG: "Ok",
                _0: {
                  NAME: "Pair",
                  VAL: [
                    match$5._0,
                    match$6._0
                  ]
                }
              };
            } else {
              let e$6 = match$6._0;
              v$4 = {
                TAG: "Error",
                _0: {
                  path: "[1]" + e$6.path,
                  message: e$6.message,
                  value: e$6.value
                }
              };
            }
          } else {
            let e$7 = match$5._0;
            v$4 = {
              TAG: "Error",
              _0: {
                path: "[0]" + e$7.path,
                message: e$7.message,
                value: e$7.value
              }
            };
          }
        }
      } else {
        v$4 = Spice.error(undefined, "Not an array", payload);
      }
      if (v$4.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: v$4._0
        };
      }
      let e$8 = v$4._0;
      return {
        TAG: "Error",
        _0: {
          path: ".Pair" + e$8.path,
          message: e$8.message,
          value: e$8.value
        }
      };
  }
}

function point_encode(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "x",
      Spice.intToJson(v.x)
    ],
    [
      "y",
      Spice.intToJson(v.y)
    ]
  ]));
}

function point_encodeJson(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "x",
      Spice.intToJson(v.x)
    ],
    [
      "y",
      Spice.intToJson(v.y)
    ]
  ]));
}

function point_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let spice_field_x = Stdlib_Option.getOr(Stdlib_Option.map(v["x"], Spice.intFromJson), Spice.error(undefined, "x" + " missing", v));
  if (spice_field_x.TAG === "Ok") {
    let spice_field_y = Stdlib_Option.getOr(Stdlib_Option.map(v["y"], Spice.intFromJson), Spice.error(undefined, "y" + " missing", v));
    if (spice_field_y.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          x: spice_field_x._0,
          y: spice_field_y._0
        }
      };
    }
    let e = spice_field_y._0;
    return Spice.error("." + ("y" + e.path), e.message, e.value);
  }
  let e$1 = spice_field_x._0;
  return Spice.error("." + ("x" + e$1.path), e$1.message, e$1.value);
}

function ext_decode(v) {
  if (v === null) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (Array.isArray(v)) {
    if (v.length === 0) {
      return Spice.error(undefined, "Expected variant, found empty array", v);
    }
    let match = v[0];
    if (typeof match === "string") {
      switch (match) {
        case "Float" :
          if (v.length !== 2) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          let v0 = Spice.floatFromJson(v[1]);
          if (v0.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                TAG: "Float",
                _0: v0._0
              }
            };
          }
          let e = v0._0;
          return {
            TAG: "Error",
            _0: {
              path: "[1]" + e.path,
              message: e.message,
              value: e.value
            }
          };
        case "List" :
          if (v.length !== 2) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          let extra = v[1];
          let v0$1 = Spice.arrayFromJson(Spice.intFromJson, extra);
          if (v0$1.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                TAG: "List",
                _0: v0$1._0
              }
            };
          }
          let e$1 = v0$1._0;
          return {
            TAG: "Error",
            _0: {
              path: "[1]" + e$1.path,
              message: e$1.message,
              value: e$1.value
            }
          };
        case "Map" :
          if (v.length !== 2) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          let extra$1 = v[1];
          let v0$2 = Spice.dictFromJson(Spice.intFromJson, extra$1);
          if (v0$2.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                TAG: "Map",
                _0: v0$2._0
              }
            };
          }
          let e$2 = v0$2._0;
          return {
            TAG: "Error",
            _0: {
              path: "[1]" + e$2.path,
              message: e$2.message,
              value: e$2.value
            }
          };
        case "Nested" :
          if (v.length !== 2) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          let v0$3 = ext_decode(v[1]);
          if (v0$3.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                TAG: "Nested",
                _0: v0$3._0
              }
            };
          }
          let e$3 = v0$3._0;
          return {
            TAG: "Error",
            _0: {
              path: "[1]" + e$3.path,
              message: e$3.message,
              value: e$3.value
            }
          };
        case "Opt" :
          if (v.length !== 2) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          let extra$2 = v[1];
          let v0$4 = Spice.optionFromJson(Spice.intFromJson, extra$2);
          if (v0$4.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                TAG: "Opt",
                _0: v0$4._0
              }
            };
          }
          let e$4 = v0$4._0;
          return {
            TAG: "Error",
            _0: {
              path: "[1]" + e$4.path,
              message: e$4.message,
              value: e$4.value
            }
          };
        case "Pair" :
          if (v.length !== 3) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          let match$1 = Spice.stringFromJson(v[1]);
          let match$2 = Spice.boolFromJson(v[2]);
          if (match$1.TAG === "Ok") {
            if (match$2.TAG === "Ok") {
              return {
                TAG: "Ok",
                _0: {
                  TAG: "Pair",
                  _0: match$1._0,
                  _1: match$2._0
                }
              };
            }
            let e$5 = match$2._0;
            return {
              TAG: "Error",
              _0: {
                path: "[2]" + e$5.path,
                message: e$5.message,
                value: e$5.value
              }
            };
          }
          let e$6 = match$1._0;
          return {
            TAG: "Error",
            _0: {
              path: "[1]" + e$6.path,
              message: e$6.message,
              value: e$6.value
            }
          };
        case "Point" :
          if (v.length !== 2) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          let v0$5 = point_decode(v[1]);
          if (v0$5.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                TAG: "Point",
                _0: v0$5._0
              }
            };
          }
          let e$7 = v0$5._0;
          return {
            TAG: "Error",
            _0: {
              path: "[1]" + e$7.path,
              message: e$7.message,
              value: e$7.value
            }
          };
        case "Rec" :
          if (v.length !== 2) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          let v$1 = v[1];
          let v$2;
          if (typeof v$1 === "object" && v$1 !== null && !Array.isArray(v$1)) {
            let spice_field_a = Stdlib_Option.getOr(Stdlib_Option.map(v$1["a"], Spice.stringFromJson), Spice.error(undefined, "a" + " missing", v$1));
            if (spice_field_a.TAG === "Ok") {
              let spice_field_b = Stdlib_Option.getOr(Stdlib_Option.map(v$1["b"], extra => Spice.optionalFieldFromJson(Spice.intFromJson, extra)), {
                TAG: "Ok",
                _0: undefined
              });
              if (spice_field_b.TAG === "Ok") {
                v$2 = {
                  TAG: "Ok",
                  _0: {
                    TAG: "Rec",
                    a: spice_field_a._0,
                    b: spice_field_b._0
                  }
                };
              } else {
                let e$8 = spice_field_b._0;
                v$2 = Spice.error("." + ("b" + e$8.path), e$8.message, e$8.value);
              }
            } else {
              let e$9 = spice_field_a._0;
              v$2 = Spice.error("." + ("a" + e$9.path), e$9.message, e$9.value);
            }
          } else {
            v$2 = Spice.error(undefined, "Not an object", v$1);
          }
          if (v$2.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: v$2._0
            };
          }
          let e$10 = v$2._0;
          return {
            TAG: "Error",
            _0: {
              path: "[1]" + e$10.path,
              message: e$10.message,
              value: e$10.value
            }
          };
        case "Renamed" :
          if (v.length !== 1) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          } else {
            return {
              TAG: "Ok",
              _0: "Renamed"
            };
          }
        case "Single" :
          if (v.length !== 2) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          let v0$6 = Spice.intFromJson(v[1]);
          if (v0$6.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                TAG: "Single",
                _0: v0$6._0
              }
            };
          }
          let e$11 = v0$6._0;
          return {
            TAG: "Error",
            _0: {
              path: "[1]" + e$11.path,
              message: e$11.message,
              value: e$11.value
            }
          };
        case "Two" :
          if (v.length !== 1) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          } else {
            return {
              TAG: "Ok",
              _0: "Two"
            };
          }
        case "Unit" :
          if (v.length !== 1) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          } else {
            return {
              TAG: "Ok",
              _0: "Unit"
            };
          }
      }
    }
    return Spice.error(undefined, "Invalid variant constructor", v[0]);
  }
  switch (typeof v) {
    case "string" :
      if (v === "Unit") {
        return {
          TAG: "Ok",
          _0: "Unit"
        };
      } else if (v === "renamed") {
        return {
          TAG: "Ok",
          _0: "Renamed"
        };
      } else if (v === "둘") {
        return {
          TAG: "Ok",
          _0: "Two"
        };
      } else {
        return Spice.error(undefined, "Invalid variant constructor", v);
      }
    case "boolean" :
    case "number" :
      return Spice.error(undefined, "Not a variant", v);
    case "object" :
      let match$3 = Object.entries(v);
      if (match$3.length !== 1) {
        return Spice.error(undefined, "Expected an object with one key", v);
      }
      let match$4 = match$3[0];
      let payload = match$4[1];
      let spice_tag = match$4[0];
      if (spice_tag === "Unit") {
        let v$3;
        v$3 = payload === null ? ({
            TAG: "Ok",
            _0: "Unit"
          }) : Spice.error(undefined, "Expected null", payload);
        if (v$3.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$3._0
          };
        }
        let e$12 = v$3._0;
        return {
          TAG: "Error",
          _0: {
            path: ".Unit" + e$12.path,
            message: e$12.message,
            value: e$12.value
          }
        };
      }
      if (spice_tag === "renamed") {
        let v$4;
        v$4 = payload === null ? ({
            TAG: "Ok",
            _0: "Renamed"
          }) : Spice.error(undefined, "Expected null", payload);
        if (v$4.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$4._0
          };
        }
        let e$13 = v$4._0;
        return {
          TAG: "Error",
          _0: {
            path: ".renamed" + e$13.path,
            message: e$13.message,
            value: e$13.value
          }
        };
      }
      if (spice_tag === "둘") {
        let v$5;
        v$5 = payload === null ? ({
            TAG: "Ok",
            _0: "Two"
          }) : Spice.error(undefined, "Expected null", payload);
        if (v$5.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$5._0
          };
        }
        let e$14 = v$5._0;
        return {
          TAG: "Error",
          _0: {
            path: ".둘" + e$14.path,
            message: e$14.message,
            value: e$14.value
          }
        };
      }
      if (spice_tag === "Single") {
        let v0$7 = Spice.intFromJson(payload);
        let v$6;
        v$6 = v0$7.TAG === "Ok" ? ({
            TAG: "Ok",
            _0: {
              TAG: "Single",
              _0: v0$7._0
            }
          }) : ({
            TAG: "Error",
            _0: v0$7._0
          });
        if (v$6.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$6._0
          };
        }
        let e$15 = v$6._0;
        return {
          TAG: "Error",
          _0: {
            path: ".Single" + e$15.path,
            message: e$15.message,
            value: e$15.value
          }
        };
      }
      if (spice_tag === "Float") {
        let v0$8 = Spice.floatFromJson(payload);
        let v$7;
        v$7 = v0$8.TAG === "Ok" ? ({
            TAG: "Ok",
            _0: {
              TAG: "Float",
              _0: v0$8._0
            }
          }) : ({
            TAG: "Error",
            _0: v0$8._0
          });
        if (v$7.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$7._0
          };
        }
        let e$16 = v$7._0;
        return {
          TAG: "Error",
          _0: {
            path: ".Float" + e$16.path,
            message: e$16.message,
            value: e$16.value
          }
        };
      }
      if (spice_tag === "Pair") {
        let v$8;
        if (Array.isArray(payload)) {
          if (payload.length !== 2) {
            v$8 = Spice.error(undefined, "Invalid number of arguments to variant constructor", payload);
          } else {
            let match$5 = Spice.stringFromJson(payload[0]);
            let match$6 = Spice.boolFromJson(payload[1]);
            if (match$5.TAG === "Ok") {
              if (match$6.TAG === "Ok") {
                v$8 = {
                  TAG: "Ok",
                  _0: {
                    TAG: "Pair",
                    _0: match$5._0,
                    _1: match$6._0
                  }
                };
              } else {
                let e$17 = match$6._0;
                v$8 = {
                  TAG: "Error",
                  _0: {
                    path: "[1]" + e$17.path,
                    message: e$17.message,
                    value: e$17.value
                  }
                };
              }
            } else {
              let e$18 = match$5._0;
              v$8 = {
                TAG: "Error",
                _0: {
                  path: "[0]" + e$18.path,
                  message: e$18.message,
                  value: e$18.value
                }
              };
            }
          }
        } else {
          v$8 = Spice.error(undefined, "Not an array", payload);
        }
        if (v$8.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$8._0
          };
        }
        let e$19 = v$8._0;
        return {
          TAG: "Error",
          _0: {
            path: ".Pair" + e$19.path,
            message: e$19.message,
            value: e$19.value
          }
        };
      }
      if (spice_tag === "Rec") {
        let v$9;
        if (typeof payload === "object" && payload !== null && !Array.isArray(payload)) {
          let spice_field_a$1 = Stdlib_Option.getOr(Stdlib_Option.map(payload["a"], Spice.stringFromJson), Spice.error(undefined, "a" + " missing", v));
          if (spice_field_a$1.TAG === "Ok") {
            let spice_field_b$1 = Stdlib_Option.getOr(Stdlib_Option.map(payload["b"], extra => Spice.optionalFieldFromJson(Spice.intFromJson, extra)), {
              TAG: "Ok",
              _0: undefined
            });
            if (spice_field_b$1.TAG === "Ok") {
              v$9 = {
                TAG: "Ok",
                _0: {
                  TAG: "Rec",
                  a: spice_field_a$1._0,
                  b: spice_field_b$1._0
                }
              };
            } else {
              let e$20 = spice_field_b$1._0;
              v$9 = Spice.error("." + ("b" + e$20.path), e$20.message, e$20.value);
            }
          } else {
            let e$21 = spice_field_a$1._0;
            v$9 = Spice.error("." + ("a" + e$21.path), e$21.message, e$21.value);
          }
        } else {
          v$9 = Spice.error(undefined, "Not an object", payload);
        }
        if (v$9.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$9._0
          };
        }
        let e$22 = v$9._0;
        return {
          TAG: "Error",
          _0: {
            path: ".Rec" + e$22.path,
            message: e$22.message,
            value: e$22.value
          }
        };
      }
      if (spice_tag === "Opt") {
        let v0$9 = Spice.optionFromJson(Spice.intFromJson, payload);
        let v$10;
        v$10 = v0$9.TAG === "Ok" ? ({
            TAG: "Ok",
            _0: {
              TAG: "Opt",
              _0: v0$9._0
            }
          }) : ({
            TAG: "Error",
            _0: v0$9._0
          });
        if (v$10.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$10._0
          };
        }
        let e$23 = v$10._0;
        return {
          TAG: "Error",
          _0: {
            path: ".Opt" + e$23.path,
            message: e$23.message,
            value: e$23.value
          }
        };
      }
      if (spice_tag === "List") {
        let v0$10 = Spice.arrayFromJson(Spice.intFromJson, payload);
        let v$11;
        v$11 = v0$10.TAG === "Ok" ? ({
            TAG: "Ok",
            _0: {
              TAG: "List",
              _0: v0$10._0
            }
          }) : ({
            TAG: "Error",
            _0: v0$10._0
          });
        if (v$11.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$11._0
          };
        }
        let e$24 = v$11._0;
        return {
          TAG: "Error",
          _0: {
            path: ".List" + e$24.path,
            message: e$24.message,
            value: e$24.value
          }
        };
      }
      if (spice_tag === "Map") {
        let v0$11 = Spice.dictFromJson(Spice.intFromJson, payload);
        let v$12;
        v$12 = v0$11.TAG === "Ok" ? ({
            TAG: "Ok",
            _0: {
              TAG: "Map",
              _0: v0$11._0
            }
          }) : ({
            TAG: "Error",
            _0: v0$11._0
          });
        if (v$12.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$12._0
          };
        }
        let e$25 = v$12._0;
        return {
          TAG: "Error",
          _0: {
            path: ".Map" + e$25.path,
            message: e$25.message,
            value: e$25.value
          }
        };
      }
      if (spice_tag === "Nested") {
        let v0$12 = ext_decode(payload);
        let v$13;
        v$13 = v0$12.TAG === "Ok" ? ({
            TAG: "Ok",
            _0: {
              TAG: "Nested",
              _0: v0$12._0
            }
          }) : ({
            TAG: "Error",
            _0: v0$12._0
          });
        if (v$13.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$13._0
          };
        }
        let e$26 = v$13._0;
        return {
          TAG: "Error",
          _0: {
            path: ".Nested" + e$26.path,
            message: e$26.message,
            value: e$26.value
          }
        };
      }
      if (spice_tag !== "Point") {
        return Spice.error(undefined, "Invalid variant constructor", v);
      }
      let v0$13 = point_decode(payload);
      let v$14;
      v$14 = v0$13.TAG === "Ok" ? ({
          TAG: "Ok",
          _0: {
            TAG: "Point",
            _0: v0$13._0
          }
        }) : ({
          TAG: "Error",
          _0: v0$13._0
        });
      if (v$14.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: v$14._0
        };
      }
      let e$27 = v$14._0;
      return {
        TAG: "Error",
        _0: {
          path: ".Point" + e$27.path,
          message: e$27.message,
          value: e$27.value
        }
      };
  }
}

function ext_encodeJson(v) {
  if (typeof v !== "object") {
    switch (v) {
      case "Unit" :
        return "Unit";
      case "Renamed" :
        return "renamed";
      case "Two" :
        return "둘";
    }
  } else {
    switch (v.TAG) {
      case "Single" :
        return Object.fromEntries([[
            "Single",
            Spice.intToJson(v._0)
          ]]);
      case "Float" :
        return Object.fromEntries([[
            "Float",
            Spice.floatToJson(v._0)
          ]]);
      case "Pair" :
        return Object.fromEntries([[
            "Pair",
            [
              Spice.stringToJson(v._0),
              Spice.boolToJson(v._1)
            ]
          ]]);
      case "Rec" :
        return Object.fromEntries([[
            "Rec",
            Object.fromEntries(Spice.filterOptional([
              [
                "a",
                Spice.stringToJson(v.a)
              ],
              [
                "b",
                Spice.optionToJson(Spice.intToJson, v.b)
              ]
            ]))
          ]]);
      case "Opt" :
        return Object.fromEntries([[
            "Opt",
            Spice.optionToNullableJson(Spice.intToJson, v._0)
          ]]);
      case "List" :
        return Object.fromEntries([[
            "List",
            Spice.arrayToJson(Spice.intToJson, v._0)
          ]]);
      case "Map" :
        return Object.fromEntries([[
            "Map",
            Spice.dictToJson(Spice.intToJson, v._0)
          ]]);
      case "Nested" :
        return Object.fromEntries([[
            "Nested",
            ext_encodeJson(v._0)
          ]]);
      case "Point" :
        return Object.fromEntries([[
            "Point",
            point_encodeJson(v._0)
          ]]);
    }
  }
}

function ext_encode(v) {
  if (typeof v !== "object") {
    switch (v) {
      case "Unit" :
        return "Unit";
      case "Renamed" :
        return "renamed";
      case "Two" :
        return "둘";
    }
  } else {
    switch (v.TAG) {
      case "Single" :
        return Object.fromEntries([[
            "Single",
            Spice.intToJson(v._0)
          ]]);
      case "Float" :
        return Object.fromEntries([[
            "Float",
            Spice.floatToJson(v._0)
          ]]);
      case "Pair" :
        return Object.fromEntries([[
            "Pair",
            [
              Spice.stringToJson(v._0),
              Spice.boolToJson(v._1)
            ]
          ]]);
      case "Rec" :
        return Object.fromEntries([[
            "Rec",
            Object.fromEntries(Spice.filterOptional([
              [
                "a",
                Spice.stringToJson(v.a)
              ],
              [
                "b",
                Spice.optionToJson(Spice.intToJson, v.b)
              ]
            ]))
          ]]);
      case "Opt" :
        return Object.fromEntries([[
            "Opt",
            Spice.optionToNullableJson(Spice.intToJson, v._0)
          ]]);
      case "List" :
        return Object.fromEntries([[
            "List",
            Spice.arrayToJson(Spice.intToJson, v._0)
          ]]);
      case "Map" :
        return Object.fromEntries([[
            "Map",
            Spice.dictToJson(Spice.intToJson, v._0)
          ]]);
      case "Nested" :
        return Object.fromEntries([[
            "Nested",
            ext_encodeJson(v._0)
          ]]);
      case "Point" :
        return Object.fromEntries([[
            "Point",
            point_encodeJson(v._0)
          ]]);
    }
  }
}

function int__encode(v) {
  if (typeof v !== "object") {
    return Object.fromEntries([[
        "type",
        "Regular"
      ]]);
  }
  switch (v.type) {
    case "Overlap" :
      return Object.fromEntries(Spice.filterOptional([
        [
          "type",
          "Overlap"
        ],
        [
          "cameraSize",
          size_encodeJson(v.cameraSize)
        ]
      ]));
    case "Full" :
      return Object.fromEntries(Spice.filterOptional([
        [
          "type",
          "full"
        ],
        [
          "screenFit",
          Spice.stringToJson(v.screenFit)
        ],
        [
          "punch_in",
          Spice.boolToJson(v.punchIn)
        ]
      ]));
    case "Point" :
      return Spice.taggedObject("type", "Point", point_encodeJson(v._0));
    case "Map" :
      return Spice.taggedObject("type", "Map", Spice.dictToJson(Spice.intToJson, v._0));
  }
}

function int__encodeJson(v) {
  if (typeof v !== "object") {
    return Object.fromEntries([[
        "type",
        "Regular"
      ]]);
  }
  switch (v.type) {
    case "Overlap" :
      return Object.fromEntries(Spice.filterOptional([
        [
          "type",
          "Overlap"
        ],
        [
          "cameraSize",
          size_encodeJson(v.cameraSize)
        ]
      ]));
    case "Full" :
      return Object.fromEntries(Spice.filterOptional([
        [
          "type",
          "full"
        ],
        [
          "screenFit",
          Spice.stringToJson(v.screenFit)
        ],
        [
          "punch_in",
          Spice.boolToJson(v.punchIn)
        ]
      ]));
    case "Point" :
      return Spice.taggedObject("type", "Point", point_encodeJson(v._0));
    case "Map" :
      return Spice.taggedObject("type", "Map", Spice.dictToJson(Spice.intToJson, v._0));
  }
}

function int__decode(v) {
  if (v === null) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (Array.isArray(v)) {
    if (v.length === 0) {
      return Spice.error(undefined, "Expected variant, found empty array", v);
    }
    let match = v[0];
    if (typeof match === "string") {
      switch (match) {
        case "Full" :
          if (v.length !== 2) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          let v$1 = v[1];
          let v$2;
          if (typeof v$1 === "object" && v$1 !== null && !Array.isArray(v$1)) {
            let spice_field_screenFit = Stdlib_Option.getOr(Stdlib_Option.map(v$1["screenFit"], Spice.stringFromJson), Spice.error(undefined, "screenFit" + " missing", v$1));
            if (spice_field_screenFit.TAG === "Ok") {
              let spice_field_punchIn = Stdlib_Option.getOr(Stdlib_Option.map(v$1["punch_in"], Spice.boolFromJson), Spice.error(undefined, "punch_in" + " missing", v$1));
              if (spice_field_punchIn.TAG === "Ok") {
                v$2 = {
                  TAG: "Ok",
                  _0: {
                    type: "Full",
                    screenFit: spice_field_screenFit._0,
                    punchIn: spice_field_punchIn._0
                  }
                };
              } else {
                let e = spice_field_punchIn._0;
                v$2 = Spice.error("." + ("punch_in" + e.path), e.message, e.value);
              }
            } else {
              let e$1 = spice_field_screenFit._0;
              v$2 = Spice.error("." + ("screenFit" + e$1.path), e$1.message, e$1.value);
            }
          } else {
            v$2 = Spice.error(undefined, "Not an object", v$1);
          }
          if (v$2.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: v$2._0
            };
          }
          let e$2 = v$2._0;
          return {
            TAG: "Error",
            _0: {
              path: "[1]" + e$2.path,
              message: e$2.message,
              value: e$2.value
            }
          };
        case "Map" :
          if (v.length !== 2) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          let extra = v[1];
          let v0 = Spice.dictFromJson(Spice.intFromJson, extra);
          if (v0.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                type: "Map",
                _0: v0._0
              }
            };
          }
          let e$3 = v0._0;
          return {
            TAG: "Error",
            _0: {
              path: "[1]" + e$3.path,
              message: e$3.message,
              value: e$3.value
            }
          };
        case "Overlap" :
          if (v.length !== 2) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          let v$3 = v[1];
          let v$4;
          if (typeof v$3 === "object" && v$3 !== null && !Array.isArray(v$3)) {
            let spice_field_cameraSize = Stdlib_Option.getOr(Stdlib_Option.map(v$3["cameraSize"], size_decode), Spice.error(undefined, "cameraSize" + " missing", v$3));
            if (spice_field_cameraSize.TAG === "Ok") {
              v$4 = {
                TAG: "Ok",
                _0: {
                  type: "Overlap",
                  cameraSize: spice_field_cameraSize._0
                }
              };
            } else {
              let e$4 = spice_field_cameraSize._0;
              v$4 = Spice.error("." + ("cameraSize" + e$4.path), e$4.message, e$4.value);
            }
          } else {
            v$4 = Spice.error(undefined, "Not an object", v$3);
          }
          if (v$4.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: v$4._0
            };
          }
          let e$5 = v$4._0;
          return {
            TAG: "Error",
            _0: {
              path: "[1]" + e$5.path,
              message: e$5.message,
              value: e$5.value
            }
          };
        case "Point" :
          if (v.length !== 2) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          let v0$1 = point_decode(v[1]);
          if (v0$1.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                type: "Point",
                _0: v0$1._0
              }
            };
          }
          let e$6 = v0$1._0;
          return {
            TAG: "Error",
            _0: {
              path: "[1]" + e$6.path,
              message: e$6.message,
              value: e$6.value
            }
          };
        case "Regular" :
          if (v.length !== 1) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          } else {
            return {
              TAG: "Ok",
              _0: "Regular"
            };
          }
      }
    }
    return Spice.error(undefined, "Invalid variant constructor", v[0]);
  }
  switch (typeof v) {
    case "string" :
      if (v === "Regular") {
        return {
          TAG: "Ok",
          _0: "Regular"
        };
      } else {
        return Spice.error(undefined, "Invalid variant constructor", v);
      }
    case "boolean" :
    case "number" :
      return Spice.error(undefined, "Not a variant", v);
    case "object" :
      let match$1 = v["type"];
      if (typeof match$1 === "string") {
        if (match$1 === "Regular") {
          return {
            TAG: "Ok",
            _0: "Regular"
          };
        }
        if (match$1 === "Overlap") {
          let spice_field_cameraSize$1 = Stdlib_Option.getOr(Stdlib_Option.map(v["cameraSize"], size_decode), Spice.error(undefined, "cameraSize" + " missing", v));
          if (spice_field_cameraSize$1.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                type: "Overlap",
                cameraSize: spice_field_cameraSize$1._0
              }
            };
          }
          let e$7 = spice_field_cameraSize$1._0;
          return Spice.error("." + ("cameraSize" + e$7.path), e$7.message, e$7.value);
        }
        if (match$1 === "full") {
          let spice_field_screenFit$1 = Stdlib_Option.getOr(Stdlib_Option.map(v["screenFit"], Spice.stringFromJson), Spice.error(undefined, "screenFit" + " missing", v));
          if (spice_field_screenFit$1.TAG === "Ok") {
            let spice_field_punchIn$1 = Stdlib_Option.getOr(Stdlib_Option.map(v["punch_in"], Spice.boolFromJson), Spice.error(undefined, "punch_in" + " missing", v));
            if (spice_field_punchIn$1.TAG === "Ok") {
              return {
                TAG: "Ok",
                _0: {
                  type: "Full",
                  screenFit: spice_field_screenFit$1._0,
                  punchIn: spice_field_punchIn$1._0
                }
              };
            }
            let e$8 = spice_field_punchIn$1._0;
            return Spice.error("." + ("punch_in" + e$8.path), e$8.message, e$8.value);
          }
          let e$9 = spice_field_screenFit$1._0;
          return Spice.error("." + ("screenFit" + e$9.path), e$9.message, e$9.value);
        }
        if (match$1 === "Point") {
          let payload = Spice.untagged("type", v);
          let v0$2 = point_decode(payload);
          if (v0$2.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                type: "Point",
                _0: v0$2._0
              }
            };
          } else {
            return {
              TAG: "Error",
              _0: v0$2._0
            };
          }
        }
        if (match$1 !== "Map") {
          return Spice.error(undefined, "Invalid variant constructor", v);
        }
        let payload$1 = Spice.untagged("type", v);
        let v0$3 = Spice.dictFromJson(Spice.intFromJson, payload$1);
        if (v0$3.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              type: "Map",
              _0: v0$3._0
            }
          };
        } else {
          return {
            TAG: "Error",
            _0: v0$3._0
          };
        }
      }
      return Spice.error(undefined, "type" + " missing", v);
  }
}

function nested_encode(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "kind",
      "SideBySide"
    ],
    [
      "position",
      poly_encodeJson(v.position)
    ],
    [
      "style",
      int__encodeJson(v.style)
    ]
  ]));
}

function nested_encodeJson(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "kind",
      "SideBySide"
    ],
    [
      "position",
      poly_encodeJson(v.position)
    ],
    [
      "style",
      int__encodeJson(v.style)
    ]
  ]));
}

function nested_decode(v) {
  if (v === null) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (Array.isArray(v)) {
    if (v.length === 0) {
      return Spice.error(undefined, "Expected variant, found empty array", v);
    }
    let match = v[0];
    if (match === "SideBySide") {
      if (v.length !== 2) {
        return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
      }
      let v$1 = v[1];
      let v$2;
      if (typeof v$1 === "object" && v$1 !== null && !Array.isArray(v$1)) {
        let spice_field_position = Stdlib_Option.getOr(Stdlib_Option.map(v$1["position"], poly_decode), Spice.error(undefined, "position" + " missing", v$1));
        if (spice_field_position.TAG === "Ok") {
          let spice_field_style = Stdlib_Option.getOr(Stdlib_Option.map(v$1["style"], int__decode), Spice.error(undefined, "style" + " missing", v$1));
          if (spice_field_style.TAG === "Ok") {
            v$2 = {
              TAG: "Ok",
              _0: {
                kind: "SideBySide",
                position: spice_field_position._0,
                style: spice_field_style._0
              }
            };
          } else {
            let e = spice_field_style._0;
            v$2 = Spice.error("." + ("style" + e.path), e.message, e.value);
          }
        } else {
          let e$1 = spice_field_position._0;
          v$2 = Spice.error("." + ("position" + e$1.path), e$1.message, e$1.value);
        }
      } else {
        v$2 = Spice.error(undefined, "Not an object", v$1);
      }
      if (v$2.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: v$2._0
        };
      }
      let e$2 = v$2._0;
      return {
        TAG: "Error",
        _0: {
          path: "[1]" + e$2.path,
          message: e$2.message,
          value: e$2.value
        }
      };
    }
    return Spice.error(undefined, "Invalid variant constructor", v[0]);
  }
  switch (typeof v) {
    case "string" :
      return Spice.error(undefined, "Invalid variant constructor", v);
    case "boolean" :
    case "number" :
      return Spice.error(undefined, "Not a variant", v);
    case "object" :
      let match$1 = v["kind"];
      if (typeof match$1 === "string") {
        if (match$1 !== "SideBySide") {
          return Spice.error(undefined, "Invalid variant constructor", v);
        }
        let spice_field_position$1 = Stdlib_Option.getOr(Stdlib_Option.map(v["position"], poly_decode), Spice.error(undefined, "position" + " missing", v));
        if (spice_field_position$1.TAG === "Ok") {
          let spice_field_style$1 = Stdlib_Option.getOr(Stdlib_Option.map(v["style"], int__decode), Spice.error(undefined, "style" + " missing", v));
          if (spice_field_style$1.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                kind: "SideBySide",
                position: spice_field_position$1._0,
                style: spice_field_style$1._0
              }
            };
          }
          let e$3 = spice_field_style$1._0;
          return Spice.error("." + ("style" + e$3.path), e$3.message, e$3.value);
        }
        let e$4 = spice_field_position$1._0;
        return Spice.error("." + ("position" + e$4.path), e$4.message, e$4.value);
      }
      return Spice.error(undefined, "kind" + " missing", v);
  }
}

function gen_encode(encoder_a) {
  return v => {
    if (typeof v !== "object") {
      return Object.fromEntries([[
          "type",
          "E"
        ]]);
    } else {
      return Object.fromEntries(Spice.filterOptional([
        [
          "type",
          "G"
        ],
        [
          "value",
          encoder_a(v.value)
        ]
      ]));
    }
  };
}

function gen_encodeJson(encoder_a) {
  return v => {
    if (typeof v !== "object") {
      return Object.fromEntries([[
          "type",
          "E"
        ]]);
    } else {
      return Object.fromEntries(Spice.filterOptional([
        [
          "type",
          "G"
        ],
        [
          "value",
          encoder_a(v.value)
        ]
      ]));
    }
  };
}

function gen_decode(decoder_a) {
  return v => {
    if (v === null) {
      return Spice.error(undefined, "Not a variant", v);
    }
    if (Array.isArray(v)) {
      if (v.length === 0) {
        return Spice.error(undefined, "Expected variant, found empty array", v);
      }
      let match = v[0];
      if (typeof match === "string") {
        switch (match) {
          case "E" :
            if (v.length !== 1) {
              return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
            } else {
              return {
                TAG: "Ok",
                _0: "E"
              };
            }
          case "G" :
            if (v.length !== 2) {
              return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
            }
            let v$1 = v[1];
            let v$2;
            if (typeof v$1 === "object" && v$1 !== null && !Array.isArray(v$1)) {
              let spice_field_value = Stdlib_Option.getOr(Stdlib_Option.map(v$1["value"], decoder_a), Spice.error(undefined, "value" + " missing", v$1));
              if (spice_field_value.TAG === "Ok") {
                v$2 = {
                  TAG: "Ok",
                  _0: {
                    type: "G",
                    value: spice_field_value._0
                  }
                };
              } else {
                let e = spice_field_value._0;
                v$2 = Spice.error("." + ("value" + e.path), e.message, e.value);
              }
            } else {
              v$2 = Spice.error(undefined, "Not an object", v$1);
            }
            if (v$2.TAG === "Ok") {
              return {
                TAG: "Ok",
                _0: v$2._0
              };
            }
            let e$1 = v$2._0;
            return {
              TAG: "Error",
              _0: {
                path: "[1]" + e$1.path,
                message: e$1.message,
                value: e$1.value
              }
            };
        }
      }
      return Spice.error(undefined, "Invalid variant constructor", v[0]);
    }
    switch (typeof v) {
      case "string" :
        if (v === "E") {
          return {
            TAG: "Ok",
            _0: "E"
          };
        } else {
          return Spice.error(undefined, "Invalid variant constructor", v);
        }
      case "boolean" :
      case "number" :
        return Spice.error(undefined, "Not a variant", v);
      case "object" :
        let match$1 = v["type"];
        if (typeof match$1 === "string") {
          if (match$1 === "E") {
            return {
              TAG: "Ok",
              _0: "E"
            };
          }
          if (match$1 !== "G") {
            return Spice.error(undefined, "Invalid variant constructor", v);
          }
          let spice_field_value$1 = Stdlib_Option.getOr(Stdlib_Option.map(v["value"], decoder_a), Spice.error(undefined, "value" + " missing", v));
          if (spice_field_value$1.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                type: "G",
                value: spice_field_value$1._0
              }
            };
          }
          let e$2 = spice_field_value$1._0;
          return Spice.error("." + ("value" + e$2.path), e$2.message, e$2.value);
        }
        return Spice.error(undefined, "type" + " missing", v);
    }
  };
}

function tree_encodeJson(v) {
  if (typeof v !== "object") {
    return "Leaf";
  } else {
    return Object.fromEntries([[
        "Node",
        Object.fromEntries(Spice.filterOptional([
          [
            "left",
            tree_encodeJson(v.left)
          ],
          [
            "right",
            tree_encodeJson(v.right)
          ],
          [
            "value",
            Spice.intToJson(v.value)
          ]
        ]))
      ]]);
  }
}

function tree_decode(v) {
  if (v === null) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (Array.isArray(v)) {
    if (v.length === 0) {
      return Spice.error(undefined, "Expected variant, found empty array", v);
    }
    let match = v[0];
    if (typeof match === "string") {
      switch (match) {
        case "Leaf" :
          if (v.length !== 1) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          } else {
            return {
              TAG: "Ok",
              _0: "Leaf"
            };
          }
        case "Node" :
          if (v.length !== 2) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          let v$1 = v[1];
          let v$2;
          if (typeof v$1 === "object" && v$1 !== null && !Array.isArray(v$1)) {
            let spice_field_left = Stdlib_Option.getOr(Stdlib_Option.map(v$1["left"], tree_decode), Spice.error(undefined, "left" + " missing", v$1));
            if (spice_field_left.TAG === "Ok") {
              let spice_field_right = Stdlib_Option.getOr(Stdlib_Option.map(v$1["right"], tree_decode), Spice.error(undefined, "right" + " missing", v$1));
              if (spice_field_right.TAG === "Ok") {
                let spice_field_value = Stdlib_Option.getOr(Stdlib_Option.map(v$1["value"], Spice.intFromJson), Spice.error(undefined, "value" + " missing", v$1));
                if (spice_field_value.TAG === "Ok") {
                  v$2 = {
                    TAG: "Ok",
                    _0: {
                      TAG: "Node",
                      left: spice_field_left._0,
                      right: spice_field_right._0,
                      value: spice_field_value._0
                    }
                  };
                } else {
                  let e = spice_field_value._0;
                  v$2 = Spice.error("." + ("value" + e.path), e.message, e.value);
                }
              } else {
                let e$1 = spice_field_right._0;
                v$2 = Spice.error("." + ("right" + e$1.path), e$1.message, e$1.value);
              }
            } else {
              let e$2 = spice_field_left._0;
              v$2 = Spice.error("." + ("left" + e$2.path), e$2.message, e$2.value);
            }
          } else {
            v$2 = Spice.error(undefined, "Not an object", v$1);
          }
          if (v$2.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: v$2._0
            };
          }
          let e$3 = v$2._0;
          return {
            TAG: "Error",
            _0: {
              path: "[1]" + e$3.path,
              message: e$3.message,
              value: e$3.value
            }
          };
      }
    }
    return Spice.error(undefined, "Invalid variant constructor", v[0]);
  }
  switch (typeof v) {
    case "string" :
      if (v === "Leaf") {
        return {
          TAG: "Ok",
          _0: "Leaf"
        };
      } else {
        return Spice.error(undefined, "Invalid variant constructor", v);
      }
    case "boolean" :
    case "number" :
      return Spice.error(undefined, "Not a variant", v);
    case "object" :
      let match$1 = Object.entries(v);
      if (match$1.length !== 1) {
        return Spice.error(undefined, "Expected an object with one key", v);
      }
      let match$2 = match$1[0];
      let payload = match$2[1];
      let spice_tag = match$2[0];
      if (spice_tag === "Leaf") {
        let v$3;
        v$3 = payload === null ? ({
            TAG: "Ok",
            _0: "Leaf"
          }) : Spice.error(undefined, "Expected null", payload);
        if (v$3.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$3._0
          };
        }
        let e$4 = v$3._0;
        return {
          TAG: "Error",
          _0: {
            path: ".Leaf" + e$4.path,
            message: e$4.message,
            value: e$4.value
          }
        };
      }
      if (spice_tag !== "Node") {
        return Spice.error(undefined, "Invalid variant constructor", v);
      }
      let v$4;
      if (typeof payload === "object" && payload !== null && !Array.isArray(payload)) {
        let spice_field_left$1 = Stdlib_Option.getOr(Stdlib_Option.map(payload["left"], tree_decode), Spice.error(undefined, "left" + " missing", v));
        if (spice_field_left$1.TAG === "Ok") {
          let spice_field_right$1 = Stdlib_Option.getOr(Stdlib_Option.map(payload["right"], tree_decode), Spice.error(undefined, "right" + " missing", v));
          if (spice_field_right$1.TAG === "Ok") {
            let spice_field_value$1 = Stdlib_Option.getOr(Stdlib_Option.map(payload["value"], Spice.intFromJson), Spice.error(undefined, "value" + " missing", v));
            if (spice_field_value$1.TAG === "Ok") {
              v$4 = {
                TAG: "Ok",
                _0: {
                  TAG: "Node",
                  left: spice_field_left$1._0,
                  right: spice_field_right$1._0,
                  value: spice_field_value$1._0
                }
              };
            } else {
              let e$5 = spice_field_value$1._0;
              v$4 = Spice.error("." + ("value" + e$5.path), e$5.message, e$5.value);
            }
          } else {
            let e$6 = spice_field_right$1._0;
            v$4 = Spice.error("." + ("right" + e$6.path), e$6.message, e$6.value);
          }
        } else {
          let e$7 = spice_field_left$1._0;
          v$4 = Spice.error("." + ("left" + e$7.path), e$7.message, e$7.value);
        }
      } else {
        v$4 = Spice.error(undefined, "Not an object", payload);
      }
      if (v$4.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: v$4._0
        };
      }
      let e$8 = v$4._0;
      return {
        TAG: "Error",
        _0: {
          path: ".Node" + e$8.path,
          message: e$8.message,
          value: e$8.value
        }
      };
  }
}

function tree_encode(v) {
  if (typeof v !== "object") {
    return "Leaf";
  } else {
    return Object.fromEntries([[
        "Node",
        Object.fromEntries(Spice.filterOptional([
          [
            "left",
            tree_encodeJson(v.left)
          ],
          [
            "right",
            tree_encodeJson(v.right)
          ],
          [
            "value",
            Spice.intToJson(v.value)
          ]
        ]))
      ]]);
  }
}

function withNull_encode(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "type",
      "N"
    ],
    [
      "b",
      Spice.optionToJson(Spice.intToJson, v.b)
    ]
  ]));
}

function withNull_encodeJson(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "type",
      "N"
    ],
    [
      "b",
      Spice.optionToJson(Spice.intToJson, v.b)
    ]
  ]));
}

function withNull_decode(v) {
  if (v === null) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (Array.isArray(v)) {
    if (v.length === 0) {
      return Spice.error(undefined, "Expected variant, found empty array", v);
    }
    let match = v[0];
    if (match === "N") {
      if (v.length !== 2) {
        return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
      }
      let v$1 = v[1];
      let v$2;
      if (typeof v$1 === "object" && v$1 !== null && !Array.isArray(v$1)) {
        let spice_field_b = Stdlib_Option.getOr(Stdlib_Option.map(v$1["b"], extra => Spice.optionalFieldFromJson(Spice.intFromJson, extra)), {
          TAG: "Ok",
          _0: undefined
        });
        if (spice_field_b.TAG === "Ok") {
          v$2 = {
            TAG: "Ok",
            _0: {
              type: "N",
              b: spice_field_b._0
            }
          };
        } else {
          let e = spice_field_b._0;
          v$2 = Spice.error("." + ("b" + e.path), e.message, e.value);
        }
      } else {
        v$2 = Spice.error(undefined, "Not an object", v$1);
      }
      if (v$2.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: v$2._0
        };
      }
      let e$1 = v$2._0;
      return {
        TAG: "Error",
        _0: {
          path: "[1]" + e$1.path,
          message: e$1.message,
          value: e$1.value
        }
      };
    }
    return Spice.error(undefined, "Invalid variant constructor", v[0]);
  }
  switch (typeof v) {
    case "string" :
      return Spice.error(undefined, "Invalid variant constructor", v);
    case "boolean" :
    case "number" :
      return Spice.error(undefined, "Not a variant", v);
    case "object" :
      let match$1 = v["type"];
      if (typeof match$1 === "string") {
        if (match$1 !== "N") {
          return Spice.error(undefined, "Invalid variant constructor", v);
        }
        let spice_field_b$1 = Stdlib_Option.getOr(Stdlib_Option.map(v["b"], extra => Spice.optionalFieldFromJson(Spice.intFromJson, extra)), {
          TAG: "Ok",
          _0: undefined
        });
        if (spice_field_b$1.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              type: "N",
              b: spice_field_b$1._0
            }
          };
        }
        let e$2 = spice_field_b$1._0;
        return Spice.error("." + ("b" + e$2.path), e$2.message, e$2.value);
      }
      return Spice.error(undefined, "type" + " missing", v);
  }
}

export {
  size_encode,
  size_encodeJson,
  size_decode,
  poly_encode,
  poly_encodeJson,
  poly_decode,
  point_encode,
  point_encodeJson,
  point_decode,
  ext_encode,
  ext_encodeJson,
  ext_decode,
  int__encode,
  int__encodeJson,
  int__decode,
  nested_encode,
  nested_encodeJson,
  nested_decode,
  gen_encode,
  gen_encodeJson,
  gen_decode,
  tree_encode,
  tree_encodeJson,
  tree_decode,
  withNull_encode,
  withNull_encodeJson,
  withNull_decode,
}
/* No side effect */
