// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function expr_decode(v) {
  if (v === null) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (Array.isArray(v)) {
    if (v.length === 0) {
      return Spice.error(undefined, "Expected variant, found empty array", v);
    }
    let match = v[0];
    if (typeof match === "string") {
      switch (match) {
        case "Add" :
          if (v.length !== 2) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          let v$1 = v[1];
          let v$2;
          if (typeof v$1 === "object" && v$1 !== null && !Array.isArray(v$1)) {
            let spice_field_left = Stdlib_Option.getOr(Stdlib_Option.map(v$1["left"], expr_decode), Spice.error(undefined, "left" + " missing", v$1));
            if (spice_field_left.TAG === "Ok") {
              let spice_field_right = Stdlib_Option.getOr(Stdlib_Option.map(v$1["right"], term_decode), Spice.error(undefined, "right" + " missing", v$1));
              if (spice_field_right.TAG === "Ok") {
                v$2 = {
                  TAG: "Ok",
                  _0: {
                    TAG: "Add",
                    left: spice_field_left._0,
                    right: spice_field_right._0
                  }
                };
              } else {
                let e = spice_field_right._0;
                v$2 = Spice.error("." + ("right" + e.path), e.message, e.value);
              }
            } else {
              let e$1 = spice_field_left._0;
              v$2 = Spice.error("." + ("left" + e$1.path), e$1.message, e$1.value);
            }
          } else {
            v$2 = Spice.error(undefined, "Not an object", v$1);
          }
          if (v$2.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: v$2._0
            };
          }
          let e$2 = v$2._0;
          return {
            TAG: "Error",
            _0: {
              path: "[1]" + e$2.path,
              message: e$2.message,
              value: e$2.value
            }
          };
        case "Neg" :
          if (v.length !== 2) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          let v0 = term_decode(v[1]);
          if (v0.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                TAG: "Neg",
                _0: v0._0
              }
            };
          }
          let e$3 = v0._0;
          return {
            TAG: "Error",
            _0: {
              path: "[1]" + e$3.path,
              message: e$3.message,
              value: e$3.value
            }
          };
        case "Num" :
          if (v.length !== 2) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          let v0$1 = Spice.intFromJson(v[1]);
          if (v0$1.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                TAG: "Num",
                _0: v0$1._0
              }
            };
          }
          let e$4 = v0$1._0;
          return {
            TAG: "Error",
            _0: {
              path: "[1]" + e$4.path,
              message: e$4.message,
              value: e$4.value
            }
          };
      }
    }
    return Spice.error(undefined, "Invalid variant constructor", v[0]);
  }
  switch (typeof v) {
    case "string" :
      return Spice.error(undefined, "Invalid variant constructor", v);
    case "boolean" :
    case "number" :
      return Spice.error(undefined, "Not a variant", v);
    case "object" :
      let match$1 = Object.entries(v);
      if (match$1.length !== 1) {
        return Spice.error(undefined, "Expected an object with one key", v);
      }
      let match$2 = match$1[0];
      let payload = match$2[1];
      let spice_tag = match$2[0];
      if (spice_tag === "Num") {
        let v0$2 = Spice.intFromJson(payload);
        let v$3;
        v$3 = v0$2.TAG === "Ok" ? ({
            TAG: "Ok",
            _0: {
              TAG: "Num",
              _0: v0$2._0
            }
          }) : ({
            TAG: "Error",
            _0: v0$2._0
          });
        if (v$3.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$3._0
          };
        }
        let e$5 = v$3._0;
        return {
          TAG: "Error",
          _0: {
            path: ".Num" + e$5.path,
            message: e$5.message,
            value: e$5.value
          }
        };
      }
      if (spice_tag === "Add") {
        let v$4;
        if (typeof payload === "object" && payload !== null && !Array.isArray(payload)) {
          let spice_field_left$1 = Stdlib_Option.getOr(Stdlib_Option.map(payload["left"], expr_decode), Spice.error(undefined, "left" + " missing", v));
          if (spice_field_left$1.TAG === "Ok") {
            let spice_field_right$1 = Stdlib_Option.getOr(Stdlib_Option.map(payload["right"], term_decode), Spice.error(undefined, "right" + " missing", v));
            if (spice_field_right$1.TAG === "Ok") {
              v$4 = {
                TAG: "Ok",
                _0: {
                  TAG: "Add",
                  left: spice_field_left$1._0,
                  right: spice_field_right$1._0
                }
              };
            } else {
              let e$6 = spice_field_right$1._0;
              v$4 = Spice.error("." + ("right" + e$6.path), e$6.message, e$6.value);
            }
          } else {
            let e$7 = spice_field_left$1._0;
            v$4 = Spice.error("." + ("left" + e$7.path), e$7.message, e$7.value);
          }
        } else {
          v$4 = Spice.error(undefined, "Not an object", payload);
        }
        if (v$4.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$4._0
          };
        }
        let e$8 = v$4._0;
        return {
          TAG: "Error",
          _0: {
            path: ".Add" + e$8.path,
            message: e$8.message,
            value: e$8.value
          }
        };
      }
      if (spice_tag !== "Neg") {
        return Spice.error(undefined, "Invalid variant constructor", v);
      }
      let v0$3 = term_decode(payload);
      let v$5;
      v$5 = v0$3.TAG === "Ok" ? ({
          TAG: "Ok",
          _0: {
            TAG: "Neg",
            _0: v0$3._0
          }
        }) : ({
          TAG: "Error",
          _0: v0$3._0
        });
      if (v$5.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: v$5._0
        };
      }
      let e$9 = v$5._0;
      return {
        TAG: "Error",
        _0: {
          path: ".Neg" + e$9.path,
          message: e$9.message,
          value: e$9.value
        }
      };
  }
}

function expr_encodeJson(v) {
  switch (v.TAG) {
    case "Num" :
      return Object.fromEntries([[
          "Num",
          Spice.intToJson(v._0)
        ]]);
    case "Add" :
      return Object.fromEntries([[
          "Add",
          Object.fromEntries(Spice.filterOptional([
            [
              "left",
              expr_encodeJson(v.left)
            ],
            [
              "right",
              term_encodeJson(v.right)
            ]
          ]))
        ]]);
    case "Neg" :
      return Object.fromEntries([[
          "Neg",
          term_encodeJson(v._0)
        ]]);
  }
}

function term_encodeJson(v) {
  if (typeof v !== "object") {
    return Object.fromEntries([[
        "op",
        "Zero"
      ]]);
  } else if (v.op === "Lit") {
    return Object.fromEntries(Spice.filterOptional([
      [
        "op",
        "Lit"
      ],
      [
        "value",
        Spice.intToJson(v.value)
      ]
    ]));
  } else {
    return Object.fromEntries(Spice.filterOptional([
      [
        "op",
        "Wrap"
      ],
      [
        "inner",
        expr_encodeJson(v.inner)
      ]
    ]));
  }
}

function term_decode(v) {
  if (v === null) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (Array.isArray(v)) {
    if (v.length === 0) {
      return Spice.error(undefined, "Expected variant, found empty array", v);
    }
    let match = v[0];
    if (typeof match === "string") {
      switch (match) {
        case "Lit" :
          if (v.length !== 2) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          let v$1 = v[1];
          let v$2;
          if (typeof v$1 === "object" && v$1 !== null && !Array.isArray(v$1)) {
            let spice_field_value = Stdlib_Option.getOr(Stdlib_Option.map(v$1["value"], Spice.intFromJson), Spice.error(undefined, "value" + " missing", v$1));
            if (spice_field_value.TAG === "Ok") {
              v$2 = {
                TAG: "Ok",
                _0: {
                  op: "Lit",
                  value: spice_field_value._0
                }
              };
            } else {
              let e = spice_field_value._0;
              v$2 = Spice.error("." + ("value" + e.path), e.message, e.value);
            }
          } else {
            v$2 = Spice.error(undefined, "Not an object", v$1);
          }
          if (v$2.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: v$2._0
            };
          }
          let e$1 = v$2._0;
          return {
            TAG: "Error",
            _0: {
              path: "[1]" + e$1.path,
              message: e$1.message,
              value: e$1.value
            }
          };
        case "Wrap" :
          if (v.length !== 2) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          let v$3 = v[1];
          let v$4;
          if (typeof v$3 === "object" && v$3 !== null && !Array.isArray(v$3)) {
            let spice_field_inner = Stdlib_Option.getOr(Stdlib_Option.map(v$3["inner"], expr_decode), Spice.error(undefined, "inner" + " missing", v$3));
            if (spice_field_inner.TAG === "Ok") {
              v$4 = {
                TAG: "Ok",
                _0: {
                  op: "Wrap",
                  inner: spice_field_inner._0
                }
              };
            } else {
              let e$2 = spice_field_inner._0;
              v$4 = Spice.error("." + ("inner" + e$2.path), e$2.message, e$2.value);
            }
          } else {
            v$4 = Spice.error(undefined, "Not an object", v$3);
          }
          if (v$4.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: v$4._0
            };
          }
          let e$3 = v$4._0;
          return {
            TAG: "Error",
            _0: {
              path: "[1]" + e$3.path,
              message: e$3.message,
              value: e$3.value
            }
          };
        case "Zero" :
          if (v.length !== 1) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          } else {
            return {
              TAG: "Ok",
              _0: "Zero"
            };
          }
      }
    }
    return Spice.error(undefined, "Invalid variant constructor", v[0]);
  }
  switch (typeof v) {
    case "string" :
      if (v === "Zero") {
        return {
          TAG: "Ok",
          _0: "Zero"
        };
      } else {
        return Spice.error(undefined, "Invalid variant constructor", v);
      }
    case "boolean" :
    case "number" :
      return Spice.error(undefined, "Not a variant", v);
    case "object" :
      let match$1 = v["op"];
      if (typeof match$1 === "string") {
        if (match$1 === "Zero") {
          return {
            TAG: "Ok",
            _0: "Zero"
          };
        }
        if (match$1 === "Lit") {
          let spice_field_value$1 = Stdlib_Option.getOr(Stdlib_Option.map(v["value"], Spice.intFromJson), Spice.error(undefined, "value" + " missing", v));
          if (spice_field_value$1.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                op: "Lit",
                value: spice_field_value$1._0
              }
            };
          }
          let e$4 = spice_field_value$1._0;
          return Spice.error("." + ("value" + e$4.path), e$4.message, e$4.value);
        }
        if (match$1 !== "Wrap") {
          return Spice.error(undefined, "Invalid variant constructor", v);
        }
        let spice_field_inner$1 = Stdlib_Option.getOr(Stdlib_Option.map(v["inner"], expr_decode), Spice.error(undefined, "inner" + " missing", v));
        if (spice_field_inner$1.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              op: "Wrap",
              inner: spice_field_inner$1._0
            }
          };
        }
        let e$5 = spice_field_inner$1._0;
        return Spice.error("." + ("inner" + e$5.path), e$5.message, e$5.value);
      }
      return Spice.error(undefined, "op" + " missing", v);
  }
}

function expr_encode(v) {
  switch (v.TAG) {
    case "Num" :
      return Object.fromEntries([[
          "Num",
          Spice.intToJson(v._0)
        ]]);
    case "Add" :
      return Object.fromEntries([[
          "Add",
          Object.fromEntries(Spice.filterOptional([
            [
              "left",
              expr_encodeJson(v.left)
            ],
            [
              "right",
              term_encodeJson(v.right)
            ]
          ]))
        ]]);
    case "Neg" :
      return Object.fromEntries([[
          "Neg",
          term_encodeJson(v._0)
        ]]);
  }
}

function term_encode(v) {
  if (typeof v !== "object") {
    return Object.fromEntries([[
        "op",
        "Zero"
      ]]);
  } else if (v.op === "Lit") {
    return Object.fromEntries(Spice.filterOptional([
      [
        "op",
        "Lit"
      ],
      [
        "value",
        Spice.intToJson(v.value)
      ]
    ]));
  } else {
    return Object.fromEntries(Spice.filterOptional([
      [
        "op",
        "Wrap"
      ],
      [
        "inner",
        expr_encodeJson(v.inner)
      ]
    ]));
  }
}

function ext_encode(v) {
  return Object.fromEntries([[
      "Clash",
      Object.fromEntries(Spice.filterOptional([
        [
          "v",
          Spice.intToJson(v.v)
        ],
        [
          "dict",
          Spice.intToJson(v.dict)
        ],
        [
          "payload",
          Spice.intToJson(v.payload)
        ],
        [
          "json_arr",
          Spice.intToJson(v.json_arr)
        ],
        [
          "spice_tag",
          Spice.intToJson(v.spice_tag)
        ],
        [
          "e",
          Spice.intToJson(v.e)
        ]
      ]))
    ]]);
}

function ext_encodeJson(v) {
  return Object.fromEntries([[
      "Clash",
      Object.fromEntries(Spice.filterOptional([
        [
          "v",
          Spice.intToJson(v.v)
        ],
        [
          "dict",
          Spice.intToJson(v.dict)
        ],
        [
          "payload",
          Spice.intToJson(v.payload)
        ],
        [
          "json_arr",
          Spice.intToJson(v.json_arr)
        ],
        [
          "spice_tag",
          Spice.intToJson(v.spice_tag)
        ],
        [
          "e",
          Spice.intToJson(v.e)
        ]
      ]))
    ]]);
}

function ext_decode(v) {
  if (v === null) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (Array.isArray(v)) {
    if (v.length === 0) {
      return Spice.error(undefined, "Expected variant, found empty array", v);
    }
    let match = v[0];
    if (match === "Clash") {
      if (v.length !== 2) {
        return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
      }
      let v$1 = v[1];
      let v$2;
      if (typeof v$1 === "object" && v$1 !== null && !Array.isArray(v$1)) {
        let spice_field_v = Stdlib_Option.getOr(Stdlib_Option.map(v$1["v"], Spice.intFromJson), Spice.error(undefined, "v" + " missing", v$1));
        if (spice_field_v.TAG === "Ok") {
          let spice_field_dict = Stdlib_Option.getOr(Stdlib_Option.map(v$1["dict"], Spice.intFromJson), Spice.error(undefined, "dict" + " missing", v$1));
          if (spice_field_dict.TAG === "Ok") {
            let spice_field_payload = Stdlib_Option.getOr(Stdlib_Option.map(v$1["payload"], Spice.intFromJson), Spice.error(undefined, "payload" + " missing", v$1));
            if (spice_field_payload.TAG === "Ok") {
              let spice_field_json_arr = Stdlib_Option.getOr(Stdlib_Option.map(v$1["json_arr"], Spice.intFromJson), Spice.error(undefined, "json_arr" + " missing", v$1));
              if (spice_field_json_arr.TAG === "Ok") {
                let spice_field_spice_tag = Stdlib_Option.getOr(Stdlib_Option.map(v$1["spice_tag"], Spice.intFromJson), Spice.error(undefined, "spice_tag" + " missing", v$1));
                if (spice_field_spice_tag.TAG === "Ok") {
                  let spice_field_e = Stdlib_Option.getOr(Stdlib_Option.map(v$1["e"], Spice.intFromJson), Spice.error(undefined, "e" + " missing", v$1));
                  if (spice_field_e.TAG === "Ok") {
                    v$2 = {
                      TAG: "Ok",
                      _0: {
                        TAG: "Clash",
                        v: spice_field_v._0,
                        dict: spice_field_dict._0,
                        payload: spice_field_payload._0,
                        json_arr: spice_field_json_arr._0,
                        spice_tag: spice_field_spice_tag._0,
                        e: spice_field_e._0
                      }
                    };
                  } else {
                    let e = spice_field_e._0;
                    v$2 = Spice.error("." + ("e" + e.path), e.message, e.value);
                  }
                } else {
                  let e$1 = spice_field_spice_tag._0;
                  v$2 = Spice.error("." + ("spice_tag" + e$1.path), e$1.message, e$1.value);
                }
              } else {
                let e$2 = spice_field_json_arr._0;
                v$2 = Spice.error("." + ("json_arr" + e$2.path), e$2.message, e$2.value);
              }
            } else {
              let e$3 = spice_field_payload._0;
              v$2 = Spice.error("." + ("payload" + e$3.path), e$3.message, e$3.value);
            }
          } else {
            let e$4 = spice_field_dict._0;
            v$2 = Spice.error("." + ("dict" + e$4.path), e$4.message, e$4.value);
          }
        } else {
          let e$5 = spice_field_v._0;
          v$2 = Spice.error("." + ("v" + e$5.path), e$5.message, e$5.value);
        }
      } else {
        v$2 = Spice.error(undefined, "Not an object", v$1);
      }
      if (v$2.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: v$2._0
        };
      }
      let e$6 = v$2._0;
      return {
        TAG: "Error",
        _0: {
          path: "[1]" + e$6.path,
          message: e$6.message,
          value: e$6.value
        }
      };
    }
    return Spice.error(undefined, "Invalid variant constructor", v[0]);
  }
  switch (typeof v) {
    case "string" :
      return Spice.error(undefined, "Invalid variant constructor", v);
    case "boolean" :
    case "number" :
      return Spice.error(undefined, "Not a variant", v);
    case "object" :
      let match$1 = Object.entries(v);
      if (match$1.length !== 1) {
        return Spice.error(undefined, "Expected an object with one key", v);
      }
      let match$2 = match$1[0];
      let payload = match$2[1];
      if (match$2[0] !== "Clash") {
        return Spice.error(undefined, "Invalid variant constructor", v);
      }
      let v$3;
      if (typeof payload === "object" && payload !== null && !Array.isArray(payload)) {
        let spice_field_v$1 = Stdlib_Option.getOr(Stdlib_Option.map(payload["v"], Spice.intFromJson), Spice.error(undefined, "v" + " missing", v));
        if (spice_field_v$1.TAG === "Ok") {
          let spice_field_dict$1 = Stdlib_Option.getOr(Stdlib_Option.map(payload["dict"], Spice.intFromJson), Spice.error(undefined, "dict" + " missing", v));
          if (spice_field_dict$1.TAG === "Ok") {
            let spice_field_payload$1 = Stdlib_Option.getOr(Stdlib_Option.map(payload["payload"], Spice.intFromJson), Spice.error(undefined, "payload" + " missing", v));
            if (spice_field_payload$1.TAG === "Ok") {
              let spice_field_json_arr$1 = Stdlib_Option.getOr(Stdlib_Option.map(payload["json_arr"], Spice.intFromJson), Spice.error(undefined, "json_arr" + " missing", v));
              if (spice_field_json_arr$1.TAG === "Ok") {
                let spice_field_spice_tag$1 = Stdlib_Option.getOr(Stdlib_Option.map(payload["spice_tag"], Spice.intFromJson), Spice.error(undefined, "spice_tag" + " missing", v));
                if (spice_field_spice_tag$1.TAG === "Ok") {
                  let spice_field_e$1 = Stdlib_Option.getOr(Stdlib_Option.map(payload["e"], Spice.intFromJson), Spice.error(undefined, "e" + " missing", v));
                  if (spice_field_e$1.TAG === "Ok") {
                    v$3 = {
                      TAG: "Ok",
                      _0: {
                        TAG: "Clash",
                        v: spice_field_v$1._0,
                        dict: spice_field_dict$1._0,
                        payload: spice_field_payload$1._0,
                        json_arr: spice_field_json_arr$1._0,
                        spice_tag: spice_field_spice_tag$1._0,
                        e: spice_field_e$1._0
                      }
                    };
                  } else {
                    let e$7 = spice_field_e$1._0;
                    v$3 = Spice.error("." + ("e" + e$7.path), e$7.message, e$7.value);
                  }
                } else {
                  let e$8 = spice_field_spice_tag$1._0;
                  v$3 = Spice.error("." + ("spice_tag" + e$8.path), e$8.message, e$8.value);
                }
              } else {
                let e$9 = spice_field_json_arr$1._0;
                v$3 = Spice.error("." + ("json_arr" + e$9.path), e$9.message, e$9.value);
              }
            } else {
              let e$10 = spice_field_payload$1._0;
              v$3 = Spice.error("." + ("payload" + e$10.path), e$10.message, e$10.value);
            }
          } else {
            let e$11 = spice_field_dict$1._0;
            v$3 = Spice.error("." + ("dict" + e$11.path), e$11.message, e$11.value);
          }
        } else {
          let e$12 = spice_field_v$1._0;
          v$3 = Spice.error("." + ("v" + e$12.path), e$12.message, e$12.value);
        }
      } else {
        v$3 = Spice.error(undefined, "Not an object", payload);
      }
      if (v$3.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: v$3._0
        };
      }
      let e$13 = v$3._0;
      return {
        TAG: "Error",
        _0: {
          path: ".Clash" + e$13.path,
          message: e$13.message,
          value: e$13.value
        }
      };
  }
}

function int__encode(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "type",
      "Clash"
    ],
    [
      "v",
      Spice.intToJson(v.v)
    ],
    [
      "dict",
      Spice.intToJson(v.dict)
    ],
    [
      "payload",
      Spice.intToJson(v.payload)
    ],
    [
      "json_arr",
      Spice.intToJson(v.json_arr)
    ],
    [
      "spice_tag",
      Spice.intToJson(v.spice_tag)
    ],
    [
      "e",
      Spice.intToJson(v.e)
    ]
  ]));
}

function int__encodeJson(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "type",
      "Clash"
    ],
    [
      "v",
      Spice.intToJson(v.v)
    ],
    [
      "dict",
      Spice.intToJson(v.dict)
    ],
    [
      "payload",
      Spice.intToJson(v.payload)
    ],
    [
      "json_arr",
      Spice.intToJson(v.json_arr)
    ],
    [
      "spice_tag",
      Spice.intToJson(v.spice_tag)
    ],
    [
      "e",
      Spice.intToJson(v.e)
    ]
  ]));
}

function int__decode(v) {
  if (v === null) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (Array.isArray(v)) {
    if (v.length === 0) {
      return Spice.error(undefined, "Expected variant, found empty array", v);
    }
    let match = v[0];
    if (match === "Clash") {
      if (v.length !== 2) {
        return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
      }
      let v$1 = v[1];
      let v$2;
      if (typeof v$1 === "object" && v$1 !== null && !Array.isArray(v$1)) {
        let spice_field_v = Stdlib_Option.getOr(Stdlib_Option.map(v$1["v"], Spice.intFromJson), Spice.error(undefined, "v" + " missing", v$1));
        if (spice_field_v.TAG === "Ok") {
          let spice_field_dict = Stdlib_Option.getOr(Stdlib_Option.map(v$1["dict"], Spice.intFromJson), Spice.error(undefined, "dict" + " missing", v$1));
          if (spice_field_dict.TAG === "Ok") {
            let spice_field_payload = Stdlib_Option.getOr(Stdlib_Option.map(v$1["payload"], Spice.intFromJson), Spice.error(undefined, "payload" + " missing", v$1));
            if (spice_field_payload.TAG === "Ok") {
              let spice_field_json_arr = Stdlib_Option.getOr(Stdlib_Option.map(v$1["json_arr"], Spice.intFromJson), Spice.error(undefined, "json_arr" + " missing", v$1));
              if (spice_field_json_arr.TAG === "Ok") {
                let spice_field_spice_tag = Stdlib_Option.getOr(Stdlib_Option.map(v$1["spice_tag"], Spice.intFromJson), Spice.error(undefined, "spice_tag" + " missing", v$1));
                if (spice_field_spice_tag.TAG === "Ok") {
                  let spice_field_e = Stdlib_Option.getOr(Stdlib_Option.map(v$1["e"], Spice.intFromJson), Spice.error(undefined, "e" + " missing", v$1));
                  if (spice_field_e.TAG === "Ok") {
                    v$2 = {
                      TAG: "Ok",
                      _0: {
                        type: "Clash",
                        v: spice_field_v._0,
                        dict: spice_field_dict._0,
                        payload: spice_field_payload._0,
                        json_arr: spice_field_json_arr._0,
                        spice_tag: spice_field_spice_tag._0,
                        e: spice_field_e._0
                      }
                    };
                  } else {
                    let e = spice_field_e._0;
                    v$2 = Spice.error("." + ("e" + e.path), e.message, e.value);
                  }
                } else {
                  let e$1 = spice_field_spice_tag._0;
                  v$2 = Spice.error("." + ("spice_tag" + e$1.path), e$1.message, e$1.value);
                }
              } else {
                let e$2 = spice_field_json_arr._0;
                v$2 = Spice.error("." + ("json_arr" + e$2.path), e$2.message, e$2.value);
              }
            } else {
              let e$3 = spice_field_payload._0;
              v$2 = Spice.error("." + ("payload" + e$3.path), e$3.message, e$3.value);
            }
          } else {
            let e$4 = spice_field_dict._0;
            v$2 = Spice.error("." + ("dict" + e$4.path), e$4.message, e$4.value);
          }
        } else {
          let e$5 = spice_field_v._0;
          v$2 = Spice.error("." + ("v" + e$5.path), e$5.message, e$5.value);
        }
      } else {
        v$2 = Spice.error(undefined, "Not an object", v$1);
      }
      if (v$2.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: v$2._0
        };
      }
      let e$6 = v$2._0;
      return {
        TAG: "Error",
        _0: {
          path: "[1]" + e$6.path,
          message: e$6.message,
          value: e$6.value
        }
      };
    }
    return Spice.error(undefined, "Invalid variant constructor", v[0]);
  }
  switch (typeof v) {
    case "string" :
      return Spice.error(undefined, "Invalid variant constructor", v);
    case "boolean" :
    case "number" :
      return Spice.error(undefined, "Not a variant", v);
    case "object" :
      let match$1 = v["type"];
      if (typeof match$1 === "string") {
        if (match$1 !== "Clash") {
          return Spice.error(undefined, "Invalid variant constructor", v);
        }
        let spice_field_v$1 = Stdlib_Option.getOr(Stdlib_Option.map(v["v"], Spice.intFromJson), Spice.error(undefined, "v" + " missing", v));
        if (spice_field_v$1.TAG === "Ok") {
          let spice_field_dict$1 = Stdlib_Option.getOr(Stdlib_Option.map(v["dict"], Spice.intFromJson), Spice.error(undefined, "dict" + " missing", v));
          if (spice_field_dict$1.TAG === "Ok") {
            let spice_field_payload$1 = Stdlib_Option.getOr(Stdlib_Option.map(v["payload"], Spice.intFromJson), Spice.error(undefined, "payload" + " missing", v));
            if (spice_field_payload$1.TAG === "Ok") {
              let spice_field_json_arr$1 = Stdlib_Option.getOr(Stdlib_Option.map(v["json_arr"], Spice.intFromJson), Spice.error(undefined, "json_arr" + " missing", v));
              if (spice_field_json_arr$1.TAG === "Ok") {
                let spice_field_spice_tag$1 = Stdlib_Option.getOr(Stdlib_Option.map(v["spice_tag"], Spice.intFromJson), Spice.error(undefined, "spice_tag" + " missing", v));
                if (spice_field_spice_tag$1.TAG === "Ok") {
                  let spice_field_e$1 = Stdlib_Option.getOr(Stdlib_Option.map(v["e"], Spice.intFromJson), Spice.error(undefined, "e" + " missing", v));
                  if (spice_field_e$1.TAG === "Ok") {
                    return {
                      TAG: "Ok",
                      _0: {
                        type: "Clash",
                        v: spice_field_v$1._0,
                        dict: spice_field_dict$1._0,
                        payload: spice_field_payload$1._0,
                        json_arr: spice_field_json_arr$1._0,
                        spice_tag: spice_field_spice_tag$1._0,
                        e: spice_field_e$1._0
                      }
                    };
                  }
                  let e$7 = spice_field_e$1._0;
                  return Spice.error("." + ("e" + e$7.path), e$7.message, e$7.value);
                }
                let e$8 = spice_field_spice_tag$1._0;
                return Spice.error("." + ("spice_tag" + e$8.path), e$8.message, e$8.value);
              }
              let e$9 = spice_field_json_arr$1._0;
              return Spice.error("." + ("json_arr" + e$9.path), e$9.message, e$9.value);
            }
            let e$10 = spice_field_payload$1._0;
            return Spice.error("." + ("payload" + e$10.path), e$10.message, e$10.value);
          }
          let e$11 = spice_field_dict$1._0;
          return Spice.error("." + ("dict" + e$11.path), e$11.message, e$11.value);
        }
        let e$12 = spice_field_v$1._0;
        return Spice.error("." + ("v" + e$12.path), e$12.message, e$12.value);
      }
      return Spice.error(undefined, "type" + " missing", v);
  }
}

function record_encode(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "v",
      Spice.intToJson(v.v)
    ],
    [
      "dict",
      Spice.intToJson(v.dict)
    ],
    [
      "e",
      Spice.intToJson(v.e)
    ],
    [
      "decoder_a",
      Spice.intToJson(v.decoder_a)
    ]
  ]));
}

function record_encodeJson(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "v",
      Spice.intToJson(v.v)
    ],
    [
      "dict",
      Spice.intToJson(v.dict)
    ],
    [
      "e",
      Spice.intToJson(v.e)
    ],
    [
      "decoder_a",
      Spice.intToJson(v.decoder_a)
    ]
  ]));
}

function record_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let spice_field_v = Stdlib_Option.getOr(Stdlib_Option.map(v["v"], Spice.intFromJson), Spice.error(undefined, "v" + " missing", v));
  if (spice_field_v.TAG === "Ok") {
    let spice_field_dict = Stdlib_Option.getOr(Stdlib_Option.map(v["dict"], Spice.intFromJson), Spice.error(undefined, "dict" + " missing", v));
    if (spice_field_dict.TAG === "Ok") {
      let spice_field_e = Stdlib_Option.getOr(Stdlib_Option.map(v["e"], Spice.intFromJson), Spice.error(undefined, "e" + " missing", v));
      if (spice_field_e.TAG === "Ok") {
        let spice_field_decoder_a = Stdlib_Option.getOr(Stdlib_Option.map(v["decoder_a"], Spice.intFromJson), Spice.error(undefined, "decoder_a" + " missing", v));
        if (spice_field_decoder_a.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              v: spice_field_v._0,
              dict: spice_field_dict._0,
              e: spice_field_e._0,
              decoder_a: spice_field_decoder_a._0
            }
          };
        }
        let e = spice_field_decoder_a._0;
        return Spice.error("." + ("decoder_a" + e.path), e.message, e.value);
      }
      let e$1 = spice_field_e._0;
      return Spice.error("." + ("e" + e$1.path), e$1.message, e$1.value);
    }
    let e$2 = spice_field_dict._0;
    return Spice.error("." + ("dict" + e$2.path), e$2.message, e$2.value);
  }
  let e$3 = spice_field_v._0;
  return Spice.error("." + ("v" + e$3.path), e$3.message, e$3.value);
}

function upper_0(s) {
  return s.toUpperCase();
}

function upper_1(json) {
  if (typeof json === "string") {
    return {
      TAG: "Ok",
      _0: json.toLowerCase()
    };
  } else {
    return Spice.error(undefined, "Not a string", json);
  }
}

let upper = [
  upper_0,
  upper_1
];

function fields_encode(v) {
  let spice_field_tuple = v.tuple;
  return Object.fromEntries(Spice.filterOptional([
    [
      "type",
      "Fields"
    ],
    [
      "name",
      upper_0(v.name)
    ],
    [
      "count",
      Spice.intToJson(v.count)
    ],
    [
      "optional",
      Spice.optionToJson(Spice.stringToJson, v.optional)
    ],
    [
      "nullable",
      Spice.nullToJson(Spice.intToJson, v.nullable)
    ],
    [
      "list",
      Spice.listToJson(Spice.intToJson, v.list)
    ],
    [
      "tuple",
      [
        Spice.intToJson(spice_field_tuple[0]),
        Spice.stringToJson(spice_field_tuple[1])
      ]
    ],
    [
      "result",
      Spice.resultToJson(Spice.intToJson, Spice.stringToJson, v.result)
    ]
  ]));
}

function fields_encodeJson(v) {
  let spice_field_tuple = v.tuple;
  return Object.fromEntries(Spice.filterOptional([
    [
      "type",
      "Fields"
    ],
    [
      "name",
      upper_0(v.name)
    ],
    [
      "count",
      Spice.intToJson(v.count)
    ],
    [
      "optional",
      Spice.optionToJson(Spice.stringToJson, v.optional)
    ],
    [
      "nullable",
      Spice.nullToJson(Spice.intToJson, v.nullable)
    ],
    [
      "list",
      Spice.listToJson(Spice.intToJson, v.list)
    ],
    [
      "tuple",
      [
        Spice.intToJson(spice_field_tuple[0]),
        Spice.stringToJson(spice_field_tuple[1])
      ]
    ],
    [
      "result",
      Spice.resultToJson(Spice.intToJson, Spice.stringToJson, v.result)
    ]
  ]));
}

function fields_decode(v) {
  if (v === null) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (Array.isArray(v)) {
    if (v.length === 0) {
      return Spice.error(undefined, "Expected variant, found empty array", v);
    }
    let match = v[0];
    if (match === "Fields") {
      if (v.length !== 2) {
        return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
      }
      let v$1 = v[1];
      let v$2;
      if (typeof v$1 === "object" && v$1 !== null && !Array.isArray(v$1)) {
        let spice_field_name = Stdlib_Option.getOr(Stdlib_Option.map(v$1["name"], upper_1), Spice.error(undefined, "name" + " missing", v$1));
        if (spice_field_name.TAG === "Ok") {
          let spice_field_count = Stdlib_Option.getOr(Stdlib_Option.map(v$1["count"], Spice.intFromJson), {
            TAG: "Ok",
            _0: 7
          });
          if (spice_field_count.TAG === "Ok") {
            let spice_field_optional = Stdlib_Option.getOr(Stdlib_Option.map(v$1["optional"], extra => Spice.optionalFieldFromJson(Spice.stringFromJson, extra)), {
              TAG: "Ok",
              _0: undefined
            });
            if (spice_field_optional.TAG === "Ok") {
              let spice_field_nullable = Stdlib_Option.getOr(Stdlib_Option.map(v$1["nullable"], extra => Spice.nullFromJson(Spice.intFromJson, extra)), Spice.error(undefined, "nullable" + " missing", v$1));
              if (spice_field_nullable.TAG === "Ok") {
                let spice_field_list = Stdlib_Option.getOr(Stdlib_Option.map(v$1["list"], extra => Spice.listFromJson(Spice.intFromJson, extra)), Spice.error(undefined, "list" + " missing", v$1));
                if (spice_field_list.TAG === "Ok") {
                  let spice_field_tuple = Stdlib_Option.getOr(Stdlib_Option.map(v$1["tuple"], json => {
                    if (!Array.isArray(json)) {
                      return Spice.error(undefined, "Not a tuple", json);
                    }
                    if (json.length !== 2) {
                      return Spice.error(undefined, "Incorrect cardinality", json);
                    }
                    let v0 = json[0];
                    let v1 = json[1];
                    let match = Spice.intFromJson(v0);
                    let match$1 = Spice.stringFromJson(v1);
                    if (match.TAG === "Ok") {
                      if (match$1.TAG === "Ok") {
                        return {
                          TAG: "Ok",
                          _0: [
                            match._0,
                            match$1._0
                          ]
                        };
                      }
                      let e = match$1._0;
                      return {
                        TAG: "Error",
                        _0: {
                          path: "[1]" + e.path,
                          message: e.message,
                          value: e.value
                        }
                      };
                    }
                    let e$1 = match._0;
                    return {
                      TAG: "Error",
                      _0: {
                        path: "[0]" + e$1.path,
                        message: e$1.message,
                        value: e$1.value
                      }
                    };
                  }), Spice.error(undefined, "tuple" + " missing", v$1));
                  if (spice_field_tuple.TAG === "Ok") {
                    let spice_field_result = Stdlib_Option.getOr(Stdlib_Option.map(v$1["result"], extra => Spice.resultFromJson(Spice.intFromJson, Spice.stringFromJson, extra)), Spice.error(undefined, "result" + " missing", v$1));
                    if (spice_field_result.TAG === "Ok") {
                      v$2 = {
                        TAG: "Ok",
                        _0: {
                          type: "Fields",
                          name: spice_field_name._0,
                          count: spice_field_count._0,
                          optional: spice_field_optional._0,
                          nullable: spice_field_nullable._0,
                          list: spice_field_list._0,
                          tuple: spice_field_tuple._0,
                          result: spice_field_result._0
                        }
                      };
                    } else {
                      let e = spice_field_result._0;
                      v$2 = Spice.error("." + ("result" + e.path), e.message, e.value);
                    }
                  } else {
                    let e$1 = spice_field_tuple._0;
                    v$2 = Spice.error("." + ("tuple" + e$1.path), e$1.message, e$1.value);
                  }
                } else {
                  let e$2 = spice_field_list._0;
                  v$2 = Spice.error("." + ("list" + e$2.path), e$2.message, e$2.value);
                }
              } else {
                let e$3 = spice_field_nullable._0;
                v$2 = Spice.error("." + ("nullable" + e$3.path), e$3.message, e$3.value);
              }
            } else {
              let e$4 = spice_field_optional._0;
              v$2 = Spice.error("." + ("optional" + e$4.path), e$4.message, e$4.value);
            }
          } else {
            let e$5 = spice_field_count._0;
            v$2 = Spice.error("." + ("count" + e$5.path), e$5.message, e$5.value);
          }
        } else {
          let e$6 = spice_field_name._0;
          v$2 = Spice.error("." + ("name" + e$6.path), e$6.message, e$6.value);
        }
      } else {
        v$2 = Spice.error(undefined, "Not an object", v$1);
      }
      if (v$2.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: v$2._0
        };
      }
      let e$7 = v$2._0;
      return {
        TAG: "Error",
        _0: {
          path: "[1]" + e$7.path,
          message: e$7.message,
          value: e$7.value
        }
      };
    }
    return Spice.error(undefined, "Invalid variant constructor", v[0]);
  }
  switch (typeof v) {
    case "string" :
      return Spice.error(undefined, "Invalid variant constructor", v);
    case "boolean" :
    case "number" :
      return Spice.error(undefined, "Not a variant", v);
    case "object" :
      let match$1 = v["type"];
      if (typeof match$1 === "string") {
        if (match$1 !== "Fields") {
          return Spice.error(undefined, "Invalid variant constructor", v);
        }
        let spice_field_name$1 = Stdlib_Option.getOr(Stdlib_Option.map(v["name"], upper_1), Spice.error(undefined, "name" + " missing", v));
        if (spice_field_name$1.TAG === "Ok") {
          let spice_field_count$1 = Stdlib_Option.getOr(Stdlib_Option.map(v["count"], Spice.intFromJson), {
            TAG: "Ok",
            _0: 7
          });
          if (spice_field_count$1.TAG === "Ok") {
            let spice_field_optional$1 = Stdlib_Option.getOr(Stdlib_Option.map(v["optional"], extra => Spice.optionalFieldFromJson(Spice.stringFromJson, extra)), {
              TAG: "Ok",
              _0: undefined
            });
            if (spice_field_optional$1.TAG === "Ok") {
              let spice_field_nullable$1 = Stdlib_Option.getOr(Stdlib_Option.map(v["nullable"], extra => Spice.nullFromJson(Spice.intFromJson, extra)), Spice.error(undefined, "nullable" + " missing", v));
              if (spice_field_nullable$1.TAG === "Ok") {
                let spice_field_list$1 = Stdlib_Option.getOr(Stdlib_Option.map(v["list"], extra => Spice.listFromJson(Spice.intFromJson, extra)), Spice.error(undefined, "list" + " missing", v));
                if (spice_field_list$1.TAG === "Ok") {
                  let spice_field_tuple$1 = Stdlib_Option.getOr(Stdlib_Option.map(v["tuple"], json => {
                    if (!Array.isArray(json)) {
                      return Spice.error(undefined, "Not a tuple", json);
                    }
                    if (json.length !== 2) {
                      return Spice.error(undefined, "Incorrect cardinality", json);
                    }
                    let v0 = json[0];
                    let v1 = json[1];
                    let match = Spice.intFromJson(v0);
                    let match$1 = Spice.stringFromJson(v1);
                    if (match.TAG === "Ok") {
                      if (match$1.TAG === "Ok") {
                        return {
                          TAG: "Ok",
                          _0: [
                            match._0,
                            match$1._0
                          ]
                        };
                      }
                      let e = match$1._0;
                      return {
                        TAG: "Error",
                        _0: {
                          path: "[1]" + e.path,
                          message: e.message,
                          value: e.value
                        }
                      };
                    }
                    let e$1 = match._0;
                    return {
                      TAG: "Error",
                      _0: {
                        path: "[0]" + e$1.path,
                        message: e$1.message,
                        value: e$1.value
                      }
                    };
                  }), Spice.error(undefined, "tuple" + " missing", v));
                  if (spice_field_tuple$1.TAG === "Ok") {
                    let spice_field_result$1 = Stdlib_Option.getOr(Stdlib_Option.map(v["result"], extra => Spice.resultFromJson(Spice.intFromJson, Spice.stringFromJson, extra)), Spice.error(undefined, "result" + " missing", v));
                    if (spice_field_result$1.TAG === "Ok") {
                      return {
                        TAG: "Ok",
                        _0: {
                          type: "Fields",
                          name: spice_field_name$1._0,
                          count: spice_field_count$1._0,
                          optional: spice_field_optional$1._0,
                          nullable: spice_field_nullable$1._0,
                          list: spice_field_list$1._0,
                          tuple: spice_field_tuple$1._0,
                          result: spice_field_result$1._0
                        }
                      };
                    }
                    let e$8 = spice_field_result$1._0;
                    return Spice.error("." + ("result" + e$8.path), e$8.message, e$8.value);
                  }
                  let e$9 = spice_field_tuple$1._0;
                  return Spice.error("." + ("tuple" + e$9.path), e$9.message, e$9.value);
                }
                let e$10 = spice_field_list$1._0;
                return Spice.error("." + ("list" + e$10.path), e$10.message, e$10.value);
              }
              let e$11 = spice_field_nullable$1._0;
              return Spice.error("." + ("nullable" + e$11.path), e$11.message, e$11.value);
            }
            let e$12 = spice_field_optional$1._0;
            return Spice.error("." + ("optional" + e$12.path), e$12.message, e$12.value);
          }
          let e$13 = spice_field_count$1._0;
          return Spice.error("." + ("count" + e$13.path), e$13.message, e$13.value);
        }
        let e$14 = spice_field_name$1._0;
        return Spice.error("." + ("name" + e$14.path), e$14.message, e$14.value);
      }
      return Spice.error(undefined, "type" + " missing", v);
  }
}

function gen_encode(encoder_a) {
  return encoder_b => (v => {
    if (typeof v !== "object") {
      return "Nothing";
    }
    switch (v.TAG) {
      case "One" :
        return Object.fromEntries([[
            "One",
            encoder_a(v._0)
          ]]);
      case "Two" :
        return Object.fromEntries([[
            "Two",
            [
              encoder_a(v._0),
              encoder_b(v._1)
            ]
          ]]);
      case "Rec" :
        return Object.fromEntries([[
            "Rec",
            Object.fromEntries(Spice.filterOptional([
              [
                "a",
                encoder_a(v.a)
              ],
              [
                "b",
                Spice.arrayToJson(encoder_b, v.b)
              ]
            ]))
          ]]);
    }
  });
}

function gen_encodeJson(encoder_a) {
  return encoder_b => (v => {
    if (typeof v !== "object") {
      return "Nothing";
    }
    switch (v.TAG) {
      case "One" :
        return Object.fromEntries([[
            "One",
            encoder_a(v._0)
          ]]);
      case "Two" :
        return Object.fromEntries([[
            "Two",
            [
              encoder_a(v._0),
              encoder_b(v._1)
            ]
          ]]);
      case "Rec" :
        return Object.fromEntries([[
            "Rec",
            Object.fromEntries(Spice.filterOptional([
              [
                "a",
                encoder_a(v.a)
              ],
              [
                "b",
                Spice.arrayToJson(encoder_b, v.b)
              ]
            ]))
          ]]);
    }
  });
}

function gen_decode(decoder_a) {
  return decoder_b => (v => {
    if (v === null) {
      return Spice.error(undefined, "Not a variant", v);
    }
    if (Array.isArray(v)) {
      if (v.length === 0) {
        return Spice.error(undefined, "Expected variant, found empty array", v);
      }
      let match = v[0];
      if (typeof match === "string") {
        switch (match) {
          case "Nothing" :
            if (v.length !== 1) {
              return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
            } else {
              return {
                TAG: "Ok",
                _0: "Nothing"
              };
            }
          case "One" :
            if (v.length !== 2) {
              return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
            }
            let v0 = decoder_a(v[1]);
            if (v0.TAG === "Ok") {
              return {
                TAG: "Ok",
                _0: {
                  TAG: "One",
                  _0: v0._0
                }
              };
            }
            let e = v0._0;
            return {
              TAG: "Error",
              _0: {
                path: "[1]" + e.path,
                message: e.message,
                value: e.value
              }
            };
          case "Rec" :
            if (v.length !== 2) {
              return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
            }
            let v$1 = v[1];
            let v$2;
            if (typeof v$1 === "object" && v$1 !== null && !Array.isArray(v$1)) {
              let spice_field_a = Stdlib_Option.getOr(Stdlib_Option.map(v$1["a"], decoder_a), Spice.error(undefined, "a" + " missing", v$1));
              if (spice_field_a.TAG === "Ok") {
                let spice_field_b = Stdlib_Option.getOr(Stdlib_Option.map(v$1["b"], extra => Spice.arrayFromJson(decoder_b, extra)), Spice.error(undefined, "b" + " missing", v$1));
                if (spice_field_b.TAG === "Ok") {
                  v$2 = {
                    TAG: "Ok",
                    _0: {
                      TAG: "Rec",
                      a: spice_field_a._0,
                      b: spice_field_b._0
                    }
                  };
                } else {
                  let e$1 = spice_field_b._0;
                  v$2 = Spice.error("." + ("b" + e$1.path), e$1.message, e$1.value);
                }
              } else {
                let e$2 = spice_field_a._0;
                v$2 = Spice.error("." + ("a" + e$2.path), e$2.message, e$2.value);
              }
            } else {
              v$2 = Spice.error(undefined, "Not an object", v$1);
            }
            if (v$2.TAG === "Ok") {
              return {
                TAG: "Ok",
                _0: v$2._0
              };
            }
            let e$3 = v$2._0;
            return {
              TAG: "Error",
              _0: {
                path: "[1]" + e$3.path,
                message: e$3.message,
                value: e$3.value
              }
            };
          case "Two" :
            if (v.length !== 3) {
              return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
            }
            let match$1 = decoder_a(v[1]);
            let match$2 = decoder_b(v[2]);
            if (match$1.TAG === "Ok") {
              if (match$2.TAG === "Ok") {
                return {
                  TAG: "Ok",
                  _0: {
                    TAG: "Two",
                    _0: match$1._0,
                    _1: match$2._0
                  }
                };
              }
              let e$4 = match$2._0;
              return {
                TAG: "Error",
                _0: {
                  path: "[2]" + e$4.path,
                  message: e$4.message,
                  value: e$4.value
                }
              };
            }
            let e$5 = match$1._0;
            return {
              TAG: "Error",
              _0: {
                path: "[1]" + e$5.path,
                message: e$5.message,
                value: e$5.value
              }
            };
        }
      }
      return Spice.error(undefined, "Invalid variant constructor", v[0]);
    }
    switch (typeof v) {
      case "string" :
        if (v === "Nothing") {
          return {
            TAG: "Ok",
            _0: "Nothing"
          };
        } else {
          return Spice.error(undefined, "Invalid variant constructor", v);
        }
      case "boolean" :
      case "number" :
        return Spice.error(undefined, "Not a variant", v);
      case "object" :
        let match$3 = Object.entries(v);
        if (match$3.length !== 1) {
          return Spice.error(undefined, "Expected an object with one key", v);
        }
        let match$4 = match$3[0];
        let payload = match$4[1];
        let spice_tag = match$4[0];
        if (spice_tag === "One") {
          let v0$1 = decoder_a(payload);
          let v$3;
          v$3 = v0$1.TAG === "Ok" ? ({
              TAG: "Ok",
              _0: {
                TAG: "One",
                _0: v0$1._0
              }
            }) : ({
              TAG: "Error",
              _0: v0$1._0
            });
          if (v$3.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: v$3._0
            };
          }
          let e$6 = v$3._0;
          return {
            TAG: "Error",
            _0: {
              path: ".One" + e$6.path,
              message: e$6.message,
              value: e$6.value
            }
          };
        }
        if (spice_tag === "Two") {
          let v$4;
          if (Array.isArray(payload)) {
            if (payload.length !== 2) {
              v$4 = Spice.error(undefined, "Invalid number of arguments to variant constructor", payload);
            } else {
              let match$5 = decoder_a(payload[0]);
              let match$6 = decoder_b(payload[1]);
              if (match$5.TAG === "Ok") {
                if (match$6.TAG === "Ok") {
                  v$4 = {
                    TAG: "Ok",
                    _0: {
                      TAG: "Two",
                      _0: match$5._0,
                      _1: match$6._0
                    }
                  };
                } else {
                  let e$7 = match$6._0;
                  v$4 = {
                    TAG: "Error",
                    _0: {
                      path: "[1]" + e$7.path,
                      message: e$7.message,
                      value: e$7.value
                    }
                  };
                }
              } else {
                let e$8 = match$5._0;
                v$4 = {
                  TAG: "Error",
                  _0: {
                    path: "[0]" + e$8.path,
                    message: e$8.message,
                    value: e$8.value
                  }
                };
              }
            }
          } else {
            v$4 = Spice.error(undefined, "Not an array", payload);
          }
          if (v$4.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: v$4._0
            };
          }
          let e$9 = v$4._0;
          return {
            TAG: "Error",
            _0: {
              path: ".Two" + e$9.path,
              message: e$9.message,
              value: e$9.value
            }
          };
        }
        if (spice_tag === "Rec") {
          let v$5;
          if (typeof payload === "object" && payload !== null && !Array.isArray(payload)) {
            let spice_field_a$1 = Stdlib_Option.getOr(Stdlib_Option.map(payload["a"], decoder_a), Spice.error(undefined, "a" + " missing", v));
            if (spice_field_a$1.TAG === "Ok") {
              let spice_field_b$1 = Stdlib_Option.getOr(Stdlib_Option.map(payload["b"], extra => Spice.arrayFromJson(decoder_b, extra)), Spice.error(undefined, "b" + " missing", v));
              if (spice_field_b$1.TAG === "Ok") {
                v$5 = {
                  TAG: "Ok",
                  _0: {
                    TAG: "Rec",
                    a: spice_field_a$1._0,
                    b: spice_field_b$1._0
                  }
                };
              } else {
                let e$10 = spice_field_b$1._0;
                v$5 = Spice.error("." + ("b" + e$10.path), e$10.message, e$10.value);
              }
            } else {
              let e$11 = spice_field_a$1._0;
              v$5 = Spice.error("." + ("a" + e$11.path), e$11.message, e$11.value);
            }
          } else {
            v$5 = Spice.error(undefined, "Not an object", payload);
          }
          if (v$5.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: v$5._0
            };
          }
          let e$12 = v$5._0;
          return {
            TAG: "Error",
            _0: {
              path: ".Rec" + e$12.path,
              message: e$12.message,
              value: e$12.value
            }
          };
        }
        if (spice_tag !== "Nothing") {
          return Spice.error(undefined, "Invalid variant constructor", v);
        }
        let v$6;
        v$6 = payload === null ? ({
            TAG: "Ok",
            _0: "Nothing"
          }) : Spice.error(undefined, "Expected null", payload);
        if (v$6.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$6._0
          };
        }
        let e$13 = v$6._0;
        return {
          TAG: "Error",
          _0: {
            path: ".Nothing" + e$13.path,
            message: e$13.message,
            value: e$13.value
          }
        };
    }
  });
}

function decodeOnly_decode(v) {
  if (v === null) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (Array.isArray(v)) {
    if (v.length === 0) {
      return Spice.error(undefined, "Expected variant, found empty array", v);
    }
    let match = v[0];
    if (typeof match === "string") {
      switch (match) {
        case "D1" :
          if (v.length !== 1) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          } else {
            return {
              TAG: "Ok",
              _0: "D1"
            };
          }
        case "D2" :
          if (v.length !== 2) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          let v0 = Spice.intFromJson(v[1]);
          if (v0.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                TAG: "D2",
                _0: v0._0
              }
            };
          }
          let e = v0._0;
          return {
            TAG: "Error",
            _0: {
              path: "[1]" + e.path,
              message: e.message,
              value: e.value
            }
          };
      }
    }
    return Spice.error(undefined, "Invalid variant constructor", v[0]);
  }
  switch (typeof v) {
    case "string" :
      if (v === "D1") {
        return {
          TAG: "Ok",
          _0: "D1"
        };
      } else {
        return Spice.error(undefined, "Invalid variant constructor", v);
      }
    case "boolean" :
    case "number" :
      return Spice.error(undefined, "Not a variant", v);
    case "object" :
      let match$1 = Object.entries(v);
      if (match$1.length !== 1) {
        return Spice.error(undefined, "Expected an object with one key", v);
      }
      let match$2 = match$1[0];
      let payload = match$2[1];
      let spice_tag = match$2[0];
      if (spice_tag === "D1") {
        let v$1;
        v$1 = payload === null ? ({
            TAG: "Ok",
            _0: "D1"
          }) : Spice.error(undefined, "Expected null", payload);
        if (v$1.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$1._0
          };
        }
        let e$1 = v$1._0;
        return {
          TAG: "Error",
          _0: {
            path: ".D1" + e$1.path,
            message: e$1.message,
            value: e$1.value
          }
        };
      }
      if (spice_tag !== "D2") {
        return Spice.error(undefined, "Invalid variant constructor", v);
      }
      let v0$1 = Spice.intFromJson(payload);
      let v$2;
      v$2 = v0$1.TAG === "Ok" ? ({
          TAG: "Ok",
          _0: {
            TAG: "D2",
            _0: v0$1._0
          }
        }) : ({
          TAG: "Error",
          _0: v0$1._0
        });
      if (v$2.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: v$2._0
        };
      }
      let e$2 = v$2._0;
      return {
        TAG: "Error",
        _0: {
          path: ".D2" + e$2.path,
          message: e$2.message,
          value: e$2.value
        }
      };
  }
}

function encodeOnly_encode(v) {
  if (typeof v !== "object") {
    return "E1";
  } else {
    return Object.fromEntries([[
        "E2",
        Spice.intToJson(v._0)
      ]]);
  }
}

function encodeOnly_encodeJson(v) {
  if (typeof v !== "object") {
    return "E1";
  } else {
    return Object.fromEntries([[
        "E2",
        Spice.intToJson(v._0)
      ]]);
  }
}

function single_encode(v) {
  return "Only";
}

function single_encodeJson(v) {
  return "Only";
}

function single_decode(v) {
  if (v === null) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (Array.isArray(v)) {
    if (v.length === 0) {
      return Spice.error(undefined, "Expected variant, found empty array", v);
    }
    let match = v[0];
    if (match === "Only") {
      if (v.length !== 1) {
        return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
      } else {
        return {
          TAG: "Ok",
          _0: "Only"
        };
      }
    }
    return Spice.error(undefined, "Invalid variant constructor", v[0]);
  }
  switch (typeof v) {
    case "string" :
      if (v === "Only") {
        return {
          TAG: "Ok",
          _0: "Only"
        };
      } else {
        return Spice.error(undefined, "Invalid variant constructor", v);
      }
    case "boolean" :
    case "number" :
      return Spice.error(undefined, "Not a variant", v);
    case "object" :
      let match$1 = Object.entries(v);
      if (match$1.length !== 1) {
        return Spice.error(undefined, "Expected an object with one key", v);
      }
      let match$2 = match$1[0];
      let payload = match$2[1];
      if (match$2[0] !== "Only") {
        return Spice.error(undefined, "Invalid variant constructor", v);
      }
      let v$1;
      v$1 = payload === null ? ({
          TAG: "Ok",
          _0: "Only"
        }) : Spice.error(undefined, "Expected null", payload);
      if (v$1.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: v$1._0
        };
      }
      let e = v$1._0;
      return {
        TAG: "Error",
        _0: {
          path: ".Only" + e.path,
          message: e.message,
          value: e.value
        }
      };
  }
}

function singleTagged_encode(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "type",
      "OnlyTagged"
    ],
    [
      "x",
      Spice.intToJson(v.x)
    ]
  ]));
}

function singleTagged_encodeJson(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "type",
      "OnlyTagged"
    ],
    [
      "x",
      Spice.intToJson(v.x)
    ]
  ]));
}

function singleTagged_decode(v) {
  if (v === null) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (Array.isArray(v)) {
    if (v.length === 0) {
      return Spice.error(undefined, "Expected variant, found empty array", v);
    }
    let match = v[0];
    if (match === "OnlyTagged") {
      if (v.length !== 2) {
        return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
      }
      let v$1 = v[1];
      let v$2;
      if (typeof v$1 === "object" && v$1 !== null && !Array.isArray(v$1)) {
        let spice_field_x = Stdlib_Option.getOr(Stdlib_Option.map(v$1["x"], Spice.intFromJson), Spice.error(undefined, "x" + " missing", v$1));
        if (spice_field_x.TAG === "Ok") {
          v$2 = {
            TAG: "Ok",
            _0: {
              type: "OnlyTagged",
              x: spice_field_x._0
            }
          };
        } else {
          let e = spice_field_x._0;
          v$2 = Spice.error("." + ("x" + e.path), e.message, e.value);
        }
      } else {
        v$2 = Spice.error(undefined, "Not an object", v$1);
      }
      if (v$2.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: v$2._0
        };
      }
      let e$1 = v$2._0;
      return {
        TAG: "Error",
        _0: {
          path: "[1]" + e$1.path,
          message: e$1.message,
          value: e$1.value
        }
      };
    }
    return Spice.error(undefined, "Invalid variant constructor", v[0]);
  }
  switch (typeof v) {
    case "string" :
      return Spice.error(undefined, "Invalid variant constructor", v);
    case "boolean" :
    case "number" :
      return Spice.error(undefined, "Not a variant", v);
    case "object" :
      let match$1 = v["type"];
      if (typeof match$1 === "string") {
        if (match$1 !== "OnlyTagged") {
          return Spice.error(undefined, "Invalid variant constructor", v);
        }
        let spice_field_x$1 = Stdlib_Option.getOr(Stdlib_Option.map(v["x"], Spice.intFromJson), Spice.error(undefined, "x" + " missing", v));
        if (spice_field_x$1.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              type: "OnlyTagged",
              x: spice_field_x$1._0
            }
          };
        }
        let e$2 = spice_field_x$1._0;
        return Spice.error("." + ("x" + e$2.path), e$2.message, e$2.value);
      }
      return Spice.error(undefined, "type" + " missing", v);
  }
}

function unicode_encode(v) {
  switch (v) {
    case "Hana" :
      return "하나";
    case "Space" :
      return "with space";
    case "Empty" :
      return "";
  }
}

function unicode_encodeJson(v) {
  switch (v) {
    case "Hana" :
      return "하나";
    case "Space" :
      return "with space";
    case "Empty" :
      return "";
  }
}

function unicode_decode(v) {
  if (v === null) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (Array.isArray(v)) {
    if (v.length === 0) {
      return Spice.error(undefined, "Expected variant, found empty array", v);
    }
    let match = v[0];
    if (typeof match === "string") {
      switch (match) {
        case "Empty" :
          if (v.length !== 1) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          } else {
            return {
              TAG: "Ok",
              _0: "Empty"
            };
          }
        case "Hana" :
          if (v.length !== 1) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          } else {
            return {
              TAG: "Ok",
              _0: "Hana"
            };
          }
        case "Space" :
          if (v.length !== 1) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          } else {
            return {
              TAG: "Ok",
              _0: "Space"
            };
          }
      }
    }
    return Spice.error(undefined, "Invalid variant constructor", v[0]);
  }
  switch (typeof v) {
    case "string" :
      if (v === "하나") {
        return {
          TAG: "Ok",
          _0: "Hana"
        };
      } else if (v === "with space") {
        return {
          TAG: "Ok",
          _0: "Space"
        };
      } else if (v === "") {
        return {
          TAG: "Ok",
          _0: "Empty"
        };
      } else {
        return Spice.error(undefined, "Invalid variant constructor", v);
      }
    case "boolean" :
    case "number" :
      return Spice.error(undefined, "Not a variant", v);
    case "object" :
      let match$1 = Object.entries(v);
      if (match$1.length !== 1) {
        return Spice.error(undefined, "Expected an object with one key", v);
      }
      let match$2 = match$1[0];
      let payload = match$2[1];
      let spice_tag = match$2[0];
      if (spice_tag === "하나") {
        let v$1;
        v$1 = payload === null ? ({
            TAG: "Ok",
            _0: "Hana"
          }) : Spice.error(undefined, "Expected null", payload);
        if (v$1.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$1._0
          };
        }
        let e = v$1._0;
        return {
          TAG: "Error",
          _0: {
            path: ".하나" + e.path,
            message: e.message,
            value: e.value
          }
        };
      }
      if (spice_tag === "with space") {
        let v$2;
        v$2 = payload === null ? ({
            TAG: "Ok",
            _0: "Space"
          }) : Spice.error(undefined, "Expected null", payload);
        if (v$2.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$2._0
          };
        }
        let e$1 = v$2._0;
        return {
          TAG: "Error",
          _0: {
            path: ".with space" + e$1.path,
            message: e$1.message,
            value: e$1.value
          }
        };
      }
      if (spice_tag !== "") {
        return Spice.error(undefined, "Invalid variant constructor", v);
      }
      let v$3;
      v$3 = payload === null ? ({
          TAG: "Ok",
          _0: "Empty"
        }) : Spice.error(undefined, "Expected null", payload);
      if (v$3.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: v$3._0
        };
      }
      let e$2 = v$3._0;
      return {
        TAG: "Error",
        _0: {
          path: "." + e$2.path,
          message: e$2.message,
          value: e$2.value
        }
      };
  }
}

function opt_encode(v) {
  if (v.TAG === "Some_") {
    return Object.fromEntries([[
        "Some_",
        Spice.optionToNullableJson(extra => Spice.optionToNullableJson(Spice.intToJson, extra), v._0)
      ]]);
  } else {
    return Object.fromEntries([[
        "Arr",
        Spice.arrayToJson(extra => Spice.optionToNullableJson(Spice.intToJson, extra), v._0)
      ]]);
  }
}

function opt_encodeJson(v) {
  if (v.TAG === "Some_") {
    return Object.fromEntries([[
        "Some_",
        Spice.optionToNullableJson(extra => Spice.optionToNullableJson(Spice.intToJson, extra), v._0)
      ]]);
  } else {
    return Object.fromEntries([[
        "Arr",
        Spice.arrayToJson(extra => Spice.optionToNullableJson(Spice.intToJson, extra), v._0)
      ]]);
  }
}

function opt_decode(v) {
  if (v === null) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (Array.isArray(v)) {
    if (v.length === 0) {
      return Spice.error(undefined, "Expected variant, found empty array", v);
    }
    let match = v[0];
    if (typeof match === "string") {
      switch (match) {
        case "Arr" :
          if (v.length !== 2) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          let extra = v[1];
          let v0 = Spice.arrayFromJson(extra => Spice.optionFromJson(Spice.intFromJson, extra), extra);
          if (v0.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                TAG: "Arr",
                _0: v0._0
              }
            };
          }
          let e = v0._0;
          return {
            TAG: "Error",
            _0: {
              path: "[1]" + e.path,
              message: e.message,
              value: e.value
            }
          };
        case "Some_" :
          if (v.length !== 2) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          let extra$1 = v[1];
          let v0$1 = Spice.optionFromJson(extra => Spice.optionFromJson(Spice.intFromJson, extra), extra$1);
          if (v0$1.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                TAG: "Some_",
                _0: v0$1._0
              }
            };
          }
          let e$1 = v0$1._0;
          return {
            TAG: "Error",
            _0: {
              path: "[1]" + e$1.path,
              message: e$1.message,
              value: e$1.value
            }
          };
      }
    }
    return Spice.error(undefined, "Invalid variant constructor", v[0]);
  }
  switch (typeof v) {
    case "string" :
      return Spice.error(undefined, "Invalid variant constructor", v);
    case "boolean" :
    case "number" :
      return Spice.error(undefined, "Not a variant", v);
    case "object" :
      let match$1 = Object.entries(v);
      if (match$1.length !== 1) {
        return Spice.error(undefined, "Expected an object with one key", v);
      }
      let match$2 = match$1[0];
      let payload = match$2[1];
      let spice_tag = match$2[0];
      if (spice_tag === "Some_") {
        let v0$2 = Spice.optionFromJson(extra => Spice.optionFromJson(Spice.intFromJson, extra), payload);
        let v$1;
        v$1 = v0$2.TAG === "Ok" ? ({
            TAG: "Ok",
            _0: {
              TAG: "Some_",
              _0: v0$2._0
            }
          }) : ({
            TAG: "Error",
            _0: v0$2._0
          });
        if (v$1.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: v$1._0
          };
        }
        let e$2 = v$1._0;
        return {
          TAG: "Error",
          _0: {
            path: ".Some_" + e$2.path,
            message: e$2.message,
            value: e$2.value
          }
        };
      }
      if (spice_tag !== "Arr") {
        return Spice.error(undefined, "Invalid variant constructor", v);
      }
      let v0$3 = Spice.arrayFromJson(extra => Spice.optionFromJson(Spice.intFromJson, extra), payload);
      let v$2;
      v$2 = v0$3.TAG === "Ok" ? ({
          TAG: "Ok",
          _0: {
            TAG: "Arr",
            _0: v0$3._0
          }
        }) : ({
          TAG: "Error",
          _0: v0$3._0
        });
      if (v$2.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: v$2._0
        };
      }
      let e$3 = v$2._0;
      return {
        TAG: "Error",
        _0: {
          path: ".Arr" + e$3.path,
          message: e$3.message,
          value: e$3.value
        }
      };
  }
}

export {
  expr_encode,
  expr_encodeJson,
  expr_decode,
  term_encode,
  term_encodeJson,
  term_decode,
  ext_encode,
  ext_encodeJson,
  ext_decode,
  int__encode,
  int__encodeJson,
  int__decode,
  record_encode,
  record_encodeJson,
  record_decode,
  upper,
  fields_encode,
  fields_encodeJson,
  fields_decode,
  gen_encode,
  gen_encodeJson,
  gen_decode,
  decodeOnly_decode,
  encodeOnly_encode,
  encodeOnly_encodeJson,
  single_encode,
  single_encodeJson,
  single_decode,
  singleTagged_encode,
  singleTagged_encodeJson,
  singleTagged_decode,
  unicode_encode,
  unicode_encodeJson,
  unicode_decode,
  opt_encode,
  opt_encodeJson,
  opt_decode,
}
/* No side effect */
